### ISSUE TITLE
Feature request: a way to determine seek is done

### ISSUE THREAD

**Issue by ElderOrb** [valbok/QtAVPlayer#13]
Taking into account asynchronous nature of seek currently it is not possible to understand when exactly it is finished (and understanding when it is finished is critical for resolving actual post-seek position). 

I see the following options to solve this: 

1. Introduce 'SeekingState' into State - this way calling code would be able to listed for state changed signal and listen for 'SeekingState' => 'PausedState' or 'SeekingState' => 'PlayingState'. The drawback is in need to preserve previous state to 'auto-pause' or 'auto-play' after seek completion. 

2. Introduce signal for 'wait' changes. Main issue with this approach is proper naming for this pretty low-level signal 

3. Make 'seek' to accept callback - feels pretty unnatural / non-Qt way. 

Any other ideas? I'm leaning towards the first option but want to hear thoughts before proceeding with implementation.

**Comment by valbok** [comment]
Thanks for ideas.

>Introduce 'SeekingState' 

Seems SeekingState is sufficient.


But just a note: states was meant to be updated immediately, it is not async, so when you call play(), it is in PlayingState right after. 
(the same as in Qt), but media status is LoadingMedia -> LoadedMedia.
Media statuses are async by default.

We would also use LoadingMedia -> LoadedMedia while seeking, or SeekingMedia -> LoadedMedia?

**Comment by ElderOrb** [comment]
hmmm... right, just checked QtAV too - it also has just 3 states. In this case adding SeekingMedia into MediaState seems like right approach.

**Comment by valbok** [comment]
also, we can also create signals like
started()
stopped()
paused()
seeked(pos)

had this idea, but decided to keep stateChanged(state) instead

**Comment by ElderOrb** [comment]
sure, it would make API less confusing for newcomers. As for me - I'm happy with listening for stateChanged / mediaStatusChanged (for seek)

**Comment by valbok** [comment]
added this https://github.com/valbok/QtAVPlayer/pull/38

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/49
