### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by awesomeerictech** [valbok/QtAVPlayer#180]
QAVAudioOutput audioOutput;
    QObject::connect(&p, &QAVPlayer::audioFrame, [&](const QAVAudioFrame &frame) {
         // Access to the data
        // Access to the data
      //   qDebug() << "data is: " << frame.data() << frame.data().size();

         audioOutput.play(frame);
    });

there seems to be an issue with the signal and slot connection resulting to audio playing for the first few seconds

**Comment by awesomeerictech** [comment]
reproduce from qml and widgets example

**Comment by valbok** [comment]
is it qt6.0?

**Comment by awesomeerictech** [comment]
yest qt 6.2.2 , it is more worse on android

**Comment by awesomeerictech** [comment]
yes qt 6.2.2 , it is more worse on android

**Comment by awesomeerictech** [comment]
video stream is okay but audio is only playing for the first few milliseconds then silent

**Comment by awesomeerictech** [comment]
/home/ericiots/eric/QtAVPlayer-avstream/src/QtAVPlayer/qavdemuxer.cpp:141:24: error: cannot initialize a parameter of type 'AVCodec *' with an rvalue of type 'const AVCodec *'
        codec.setCodec(avcodec_find_decoder_by_name("h264_mediacodec"));

**Comment by awesomeerictech** [comment]
QtAVPlayer-avstream/src/QtAVPlayer/qavdemuxer.cpp:141:24: error: cannot initialize a parameter of type 'AVCodec *' with an rvalue of type 'const AVCodec *'
        codec.setCodec(avcodec_find_decoder_by_name("h264_mediacodec"));

**Comment by awesomeerictech** [comment]
: PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
I gralloc : gralloc_unregister_buffer hnd=0x8e05f780, share_fd=71, share_attr_fd=72, magic=51647890, format=1, internal_format=1, byte_stride=1920, flags=4, usage=0xb00, size=1570560, width=480, height=818, internalWidth=480, internalHeight=818, stride=480, base=0x8c100000, writeOwner=0, attr_base=0xffffffff, yuv_info=1, fd=-1, buf_idx=0, offset=0, min_pgsz=4096, phyaddr=0
I gralloc : gralloc_unregister_buffer hnd=0x8e05f840, share_fd=73, share_attr_fd=74, magic=51647890, format=1, internal_format=1, byte_stride=1920, flags=4, usage=0xb00, size=1570560, width=480, height=818, internalWidth=480, internalHeight=818, stride=480, base=0x8bf80000, writeOwner=0, attr_base=0xffffffff, yuv_info=1, fd=-1, buf_idx=0, offset=0, min_pgsz=4096, phyaddr=0
I gralloc : gralloc_unregister_buffer hnd=0x8e05f600, share_fd=69, share_attr_fd=70, magic=51647890, format=1, internal_format=1, byte_stride=1920, flags=4, usage=0xb00, size=1570560, width=480, height=818, internalWidth=480, internalHeight=818, stride=480, base=0x8c280000, writeOwner=0, attr_base=0xffffffff, yuv_info=1, fd=-1, buf_idx=0, offset=0, min_pgsz=4096, phyaddr=0
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
W libEGL  : EGLNativeWindowType 0x8e150808 disconnect failed
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
D libqml_video_armeabi-v7a.so: stateChanged StoppedState LoadedMedia
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer
I AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
D libqml_video_armeabi-v7a.so: mediaStatusChanged NoMedia StoppedState
D libqml_video_armeabi-v7a.so: durationChanged 0
W libc    : check core file limit, limited=1
I libc    : Set DISDUMPABLE SUCCESS
F libc    : Fatal s

**Comment by awesomeerictech** [comment]
AudioTrack: stop  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D AudioTrack: stop() called with 2 frames delivered
I AudioTrack: start  mClientUid:10148 mClientPid:26041  mSessionId:409 app name:org.qtproject.example.qml_video
D         : PlayerBase::stop() from IPlayer

**Comment by valbok** [comment]
android on qt6 even not tested. will do

**Comment by awesomeerictech** [comment]
the above logs are from android armv7

**Comment by awesomeerictech** [comment]
> there is a bug in qtmm 6, not fixed yet, could not find workaround, they use gst for low latency audio and appsrc.

is it not fixed in 6.2.2?

**Comment by awesomeerictech** [comment]
> there is a bug in qtmm 6, not fixed yet, could not find workaround, they use gst for low latency audio and appsrc.

obviously qt uses gst backend in linux , so we need a workaround for that since the backend is there to stay

**Comment by valbok** [comment]
can you check if QSoundEffect works for you?

**Comment by awesomeerictech** [comment]
works! , as below qt 6.2.2

#include <QCoreApplication>
#include <QSoundEffect>
#include <QUrl>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    QSoundEffect effect;
    effect.setSource(QUrl::fromLocalFile("/mydir/QtAVPlayer/tests/auto/integration/testdata/test.wav"));
    effect.setLoopCount(QSoundEffect::Infinite);
    effect.setVolume(0.25f);
    effect.play();



    return a.exec();
}

**Comment by awesomeerictech** [comment]
how do i use QSoundEffect to get the audio working?

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/190

**Comment by valbok** [comment]
> QtAVPlayer-avstream/src/QtAVPlayer/qavdemuxer.cpp:141:24: error: cannot initialize a parameter of type 'AVCodec *' with an rvalue of type 'const AVCodec *' codec.setCodec(avcodec_find_decoder_by_name("h264_mediacodec"));

https://github.com/valbok/QtAVPlayer/issues/191
