### ISSUE TITLE
Android and Qt6

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#182]

**Comment by awesomeerictech** [comment]
qavdemuxer.cpp:138:18: error: cannot initialize a variable of type 'AVCodec *' with an rvalue of type 'const AVCodec *'
        AVCodec *mycodec = avcodec_find_decoder_by_name("h264_mediacodec");
                 ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by awesomeerictech** [comment]
please mark this as closed, the player is working fine in android than even linux.

**Comment by valbok** [comment]
thanks you checked it.
