### ISSUE TITLE
RENAME HEADERS

### ISSUE THREAD

**Issue by awesomeerictech** [valbok/QtAVPlayer#186]
some headers are included as #include <QtAVPlayer/headername> instead of #include "headername"

**Comment by valbok** [comment]
<QtAVPlayer/headername>
it is qt standard to include public headers, from module.

**Comment by awesomeerictech** [comment]
I know that, from your source code it is not important to do that since the module doesn't exist yet.

**Comment by valbok** [comment]
could not understand where is the issue here

**Comment by awesomeerictech** [comment]
#include <QtAVPlayer/headername> won't compile because QtAVPlayer does not exist yet, just change all the includes to #include "headername" in all your sources because the header files exist in the same directory , it is tedious work but it is worth it.

**Comment by valbok** [comment]
do you use files outside of the module?
when you build the module, all files will be installed by syncqt

**Comment by awesomeerictech** [comment]
> do you use files outside of the module? when you build the module, all files will be installed by syncqt

That is not the issue, the issue is that you can't #include <QtAVPlayer/headername> during building , that can only be done after building the module , replace all #include <QtAVPlayer/headername> with #include "headername" in all your sources because the header files exist in the same directory

**Comment by valbok** [comment]
first you need to build the module. after that you can use headers outside.
Inside module it works correctly, otherwise nothing would be built.

**Comment by awesomeerictech** [comment]
> first you need to build the module. after that you can use headers outside. Inside module it works correctly, otherwise nothing would be built.

you have already included the #include <QtAVPlayer/headername> in the module that's what i am requesting you to replace with #include "headername" in all your sources because the header files exist in the same directory

**Comment by awesomeerictech** [comment]
for instance look at qavframe.h 

#ifndef QAVFRAME_H
#define QAVFRAME_H

#include <QObject>
#include <QSharedPointer>
#include <QScopedPointer>
#include <QtAVPlayer/qtavplayerglobal.h>

extern "C" {
#include <libavutil/frame.h>
}

you can't include #include <QtAVPlayer/qtavplayerglobal.h> and it doesn't compile just replace it with #include "qtavplayerglobal.h"

**Comment by valbok** [comment]
show me the error what you received and how you used it.

**Comment by awesomeerictech** [comment]
the error is simple #include <QtAVPlayer/qtavplayerglobal.h> not found but when i replace with #include "qtavplayerglobal.h" it compiles successfully, the problem with you is that you have already installed QtAVPlayer so the error will never appear, now put yourself in the shoes of a person compiling the project for the first time , just compile time errors , quite discouraging isn't it? It is also not good idea to do so.

**Comment by valbok** [comment]
if it is not found, means something went wrong.
there are some CI github actions, https://github.com/valbok/QtAVPlayer/pull/192/checks
as you can see even on empty, clean env it is compiled and tested.
Because when you call "make" of module, it will call syncqt which will copy all public headers to the module's path.
maybe you forget to call `make install` if you build with standalone Qt.
