### ISSUE TITLE
AUDIO ERROR

### ISSUE THREAD

**Issue by awesomeerictech** [valbok/QtAVPlayer#189]
From the code snippet below the program only enters if block once (qavaudiooutput.cpp),forcing it to do so makes GSTREAMER crash  same applies to android.

 if (!audioOutput || audioOutput->format() != fmt || audioOutput->state() == QAudio::StoppedState) {
             qDebug() <<"entering if block" << Qt::endl;
           audioOutput.reset(new AudioOutput(fmt));
            QObject::connect(audioOutput.data(), &AudioOutput::stateChanged, audioOutput.data(),
                [&](QAudio::State state) {
                    switch (state) {
                        case QAudio::StoppedState:
                            if (audioOutput->error() != QAudio::NoError)
                                qWarning() << "QAudioOutput stopped:" << audioOutput->error();
                            break;
                        default:
                            break;
                    }
                });
            device = audioOutput->start();
        }

        {

            qDebug() <<"did not enter if block" << Qt::endl;
        }

**Comment by valbok** [comment]
AudioOutput should be created once, and qDebug() <<"entering if block" << Qt::endl;
should be once
