### ISSUE TITLE
qavdemuxer.cpp:138:18: error: cannot initialize a variable of type 'AVCodec *' 

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#191]
qavdemuxer.cpp:138:18: error: cannot initialize a variable of type 'AVCodec *' with an rvalue of type 'const AVCodec *'
AVCodec *mycodec = avcodec_find_decoder_by_name("h264_mediacodec");

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/192

**Comment by awesomeerictech** [comment]
I found out that the issue is FFMPEG snapshot , FFMPEG 4.4.1 works fine, i tested that thoroughly yesterday.

**Comment by awesomeerictech** [comment]
i used ffmpeg from ffpegkit from https://github.com/tanersener/ffmpeg-kit and the error appeared only to realize that it came from ffmpeg after compiling ffmpeg with https://github.com/Javernaut/ffmpeg-android-maker
