### ISSUE TITLE
QtAVPlayer as the library

### ISSUE THREAD

**Issue by ElderOrb** [valbok/QtAVPlayer#2]
At the moment QtAVPlayer is 'Qt module', but there are some cases where it is more convenient to use it as the library so would be helpful if it could provide related pro / pri file.

**Comment by valbok** [comment]
Hi, could you please check if it would be possible to use the lib from modules? And maybe it is more convenient to provide just a lib with install path instead of the module.

**Comment by ElderOrb** [comment]
Actually for my particular case (where I need to be able to build against custom ffmpeg(s)) library is the only way. Moreover developing QtAVPlayer as a library should be much more convenient. So, if I would have to selected between module-only vs library-only I would vote for library only. 

Btw, here is my quick-n-dirty approach for turning QtAV into library: 

https://github.com/ElderOrb/QtAVPlayer/commit/0738a4114e3a036dda51aef872bc3d2709ffc589

..  and here is the sample of using such a library: 

https://github.com/ElderOrb/QtAVPlayer/commit/1d93b40c7e4d9fab20c9fa8f242d35ed73bc3f3b

note: this is heavily experimental & very ugly.

**Comment by ElderOrb** [comment]
After some thinking... if there are some secret keys allowing to install QtAVPlayer as the module into custom location - it might be indistinguishable from 'library' if included into top-level pro file in similar way as I did for QtAVPlayer-as-the-library. Although not sure result will be cleaner than what I did :). 

Another note - at the moment QtAVPlayer autodect features it needs using modules feature (via json files). Library doesn't have such a mechanism (or I'm wrong?) so it would be nice to: 
1) get some alternative allowing to simplify pri / pro file usage
2) with ability to explicitly control enabling / disabling particular features
3) and ability to specify FFMPEG path

**Comment by valbok** [comment]
I would get rid of qmake and use cmake instead.

**Comment by valbok** [comment]
```/opt/cmake-3.19.2/bin/cmake .. -DCMAKE_PREFIX_PATH=/opt/dev/qtbase/lib/cmake/Qt5 -DCMAKE_INSTALL_PREFIX=/opt/QtAVPlayer/install -DCMAKE_LIBRARY_PATH=/opt/dev/qtbase/lib```

can you check if this works? Creating a lib, which can be used in pro files

**Comment by ElderOrb** [comment]
Sure, will check!

**Comment by ElderOrb** [comment]
Getting this on windows: 

D:\Projects\QtAVPlayer-clean>cmake -DCMAKE_PREFIX_PATH=D:/Qt/5.12.10/msvc2017_64/lib/cmake/Qt5 -DCMAKE_LIBRARY_PATH=D:/Qt/5.12.10/msvc2017_64/lib DCMAKE_INSTALL_PREFIX=D:/Projects/QtAVPlayer-clean/1            CMake Error: The source directory "D:/Projects/QtAVPlayer-clean/DCMAKE_INSTALL_PREFIX=D:/Projects/QtAVPlayer-clean/1" does not exist.                                                                             Specify --help for usage, or press the help button on the CMake GUI.

**Comment by ElderOrb** [comment]
Oops, the issue was due to non-clean folder.

**Comment by ElderOrb** [comment]
CMake never liked me.... :(

-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/Projects/QtAVPlayer-clean/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):nmake -f Makefile /nologo cmTC_10a70\fast && 	"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"  -f CMakeFiles\cmTC_10a70.dir\build.make /nologo -L                  CMakeFiles\cmTC_10a70.dir\build
    Building C object CMakeFiles/cmTC_10a70.dir/testCCompiler.c.obj
    	"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\cmTC_10a70.dir\testCCompiler.c.obj.d --working-dir=D:\Projects\QtAVPlayer-clean\build\CMakeFiles\CMakeTmp --filter-prefix="Note: including file: " -- C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @C:\Users\ai\AppData\Local\Temp\nm6C95.tmp
    testCCompiler.c
    Linking C executable cmTC_10a70.exe
    	"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_10a70.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests -- C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\cmTC_10a70.dir\objects1.rsp @C:\Users\ai\AppData\Local\Temp\nm6D04.tmp
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_10a70.dir/manifest.res CMakeFiles\cmTC_10a70.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specifiedNMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"' : return code '0xffffffff'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
    Stop.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "D:/Projects/QtAVPlayer-clean/build/CMakeFiles/CMakeOutput.log".
See also "D:/Projects/QtAVPlayer-clean/build/CMakeFiles/CMakeError.log".

**Comment by ElderOrb** [comment]
... and this is from VS 2019 environment: 

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "D:/Projects/QtAVPlayer-clean/build/CMakeFiles/CMakeOutput.log".
See also "D:/Projects/QtAVPlayer-clean/build/CMakeFiles/CMakeError.log".

**Comment by ElderOrb** [comment]
... and this is from WSL/Ubuntu 18: 

ai@ELDERORB:~/Projects/QtAVPlayer-upstream/build$ cmake .. -DCMAKE_PREFIX_PATH=~/Qt/5.12.10/gcc_64/lib/cmake/Qt5 -DCMAKE_LIBRARY_PATH=~/Qt/5.12.10/gcc_64/lib -DCMAKE_INCLUDE_PATH=~/Projects/qctools/ffmpeg/include -DCMAKE_INSTALL_PREFIX=~/Pr
ojects/QtAVPlayer-upstream/1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ai/Projects/QtAVPlayer-upstream/build
ai@ELDERORB:~/Projects/QtAVPlayer-upstream/build$ make
[  4%] Automatic MOC for target QtAVPlayer
[  4%] Built target QtAVPlayer_autogen
[  8%] Building CXX object src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/QtAVPlayer_autogen/mocs_compilation.cpp.o
[ 12%] Building CXX object src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavdemuxer.cpp.o
In file included from /home/ai/Qt/5.12.10/gcc_64/include/QtCore/qnamespace.h:43:0,
                 from /home/ai/Qt/5.12.10/gcc_64/include/QtCore/qobjectdefs.h:48,
                 from /home/ai/Qt/5.12.10/gcc_64/include/QtCore/qobject.h:46,
                 from /home/ai/Qt/5.12.10/gcc_64/include/QtCore/QObject:1,
                 from /home/ai/Projects/QtAVPlayer-upstream/src/QtAVPlayer/qavframe.h:11,
                 from /home/ai/Projects/QtAVPlayer-upstream/src/QtAVPlayer/qavpacket_p.h:22,
                 from /home/ai/Projects/QtAVPlayer-upstream/src/QtAVPlayer/qavdemuxer_p.h:22,
                 from /home/ai/Projects/QtAVPlayer-upstream/src/QtAVPlayer/qavdemuxer.cpp:8:
/home/ai/Qt/5.12.10/gcc_64/include/QtCore/qglobal.h:86:30: error: division by zero in #if
 #define QT_CONFIG(feature) (1/QT_FEATURE_##feature == 1)
                              ^
/home/ai/Projects/QtAVPlayer-upstream/src/QtAVPlayer/qavdemuxer.cpp:14:5: note: in expansion of macro ‘QT_CONFIG’
 #if QT_CONFIG(va_x11) && QT_CONFIG(opengl)
     ^~~~~~~~~
/home/ai/Qt/5.12.10/gcc_64/include/QtCore/qglobal.h:86:30: error: division by zero in #if
 #define QT_CONFIG(feature) (1/QT_FEATURE_##feature == 1)
                              ^
/home/ai/Projects/QtAVPlayer-upstream/src/QtAVPlayer/qavdemuxer.cpp:18:5: note: in expansion of macro ‘QT_CONFIG’
 #if QT_CONFIG(va_drm) && QT_CONFIG(egl)
     ^~~~~~~~~
src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/build.make:89: recipe for target 'src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavdemuxer.cpp.o' failed
make[2]: *** [src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavdemuxer.cpp.o] Error 1
CMakeFiles/Makefile2:166: recipe for target 'src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/all' failed
make[1]: *** [src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by valbok** [comment]
for ubuntu, did you try on clean setup?
src/QtAVPlayer/qavplayer-config_p.h.in and
build/src/QtAVPlayer/qtQtAVPlayer-config_p.h must exist

**Comment by ElderOrb** [comment]
> for ubuntu, did you try on clean setup?
> src/QtAVPlayer/qavplayer-config_p.h.in and
> build/src/QtAVPlayer/qtQtAVPlayer-config_p.h must exist

Just retried after 'git clean -dxf' and got the same error. 

 >> src/QtAVPlayer/qavplayer-config_p.h.in and 

this one exists

>> build/src/QtAVPlayer/qtQtAVPlayer-config_p.h must exist

this one too

**Comment by ElderOrb** [comment]
Interestingly, my approach to turning QtAVPlayer to library works. Moreover, the latest changes eliminated need in custom header - I can use upstream master with custom pro file, which is great!. Not so interested in fixing cmake atm.

**Comment by ElderOrb** [comment]
Forgot to mention, now sure what did change, but cmake started working for me, at least on windows!
