### ISSUE TITLE
NO SOUND HLS STREAM QT 6.2

### ISSUE THREAD

**Issue by awesomeerictech** [valbok/QtAVPlayer#214]
The audio plays only for the first few seconds then stops

**Comment by valbok** [comment]
could you please provide url? also any errors returned?
did you make sure that this url works with vlc or something?

**Comment by awesomeerictech** [comment]
No sound from all URLs , test with https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by awesomeerictech** [comment]
I wish it worked well with qtavplayer

**Comment by awesomeerictech** [comment]
issue resolved by prolonging http keep-alive seconds on android and linux

**Comment by awesomeerictech** [comment]
there is sound in HLS streams,tested with qt 6.2.3 android and linux, please close the issue
