### ISSUE TITLE
RTMP/RTMPS streams play failure

### ISSUE THREAD

**Issue by awesomeerictech** [valbok/QtAVPlayer#215]

**Comment by valbok** [comment]
could you please provide example url?

**Comment by awesomeerictech** [comment]
I am using my custom RTMP(S) URL and it is working for all the other players vlc,ffplay and mdk-sdk , i have tested thoroughly and ffmpeg is compiled with openssl , the problem is not my url but rather qtavplayer

**Comment by awesomeerictech** [comment]
test with nginx rtmp module

**Comment by awesomeerictech** [comment]
[h264 @ 0x7f1c3800aec0] co located POCs unavailable

**Comment by awesomeerictech** [comment]
rtmp and rtmps streams are now playing , really fast!, please close the issue.
