### ISSUE TITLE
Unable to play MPEG-PS

### ISSUE THREAD

**Issue by bloxgate** [valbok/QtAVPlayer#225]
Hello,

After seeing #222 get merged today I attempted to run the qml_video example on some videos which I'd previously had some problems with. Most of them worked fine now (thanks for that!), however I'm seeing no video output at all when attempting to play a video that is encoded with MPEG-PS.

Here's some console output from one of the videos:
```
.\qml_video.exe C:\Users\Gregory\Videos\format-test\star_trails.mpeg
stateChanged PlayingState NoMedia
[mpeg @ 000001B8E40BD740] start time for stream 0 is not set in estimate_timings_from_pts
mpeg2video : supported hardware device contexts:
    dxva2
    d3d11va
    cuda
Found hardware device context: d3d11va
mediaStatusChanged LoadedMedia PlayingState
Video streams: 1
[ 1 ] QMap()
Audio streams: 1
[ 2 ] QMap()
Subtitle streams: 0
durationChanged 21239
stateChanged StoppedState EndOfMedia
mediaStatusChanged EndOfMedia StoppedState
mediaStatusChanged NoMedia StoppedState
durationChanged 0
```

And here's ffprobe output for the file:
```
.\ffprobe -hide_banner C:\Users\Gregory\Videos\format-test\star_trails.mpeg
[mpeg @ 000002D19107E240] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpeg, from 'C:\Users\Gregory\Videos\format-test\star_trails.mpeg':
  Duration: 00:00:21.24, start: 0.529978, bitrate: 1359 kb/s
  Stream #0:0[0x1bf]: Data: dvd_nav_packet
  Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 49152 vbv_delay: N/A
  Stream #0:2[0x1c0]: Audio: mp2, 48000 Hz, stereo, s16p, 384 kb/s
Unsupported codec with id 98312 for input stream 0
```

FFmpeg is able to handle the file just fine, and can transcode it to other formats without issue.

If needed I can send the video file to you.

**Comment by valbok** [comment]
hi, thanks for submitting this.
Could you please test with QT_AVPLAYER_NO_HWDEVICE=1 ?
Also, you could save frame to file and check if the frame is valid.
QVideoFrame f = frame;
f.toImage().save("frame.jpg");

**Comment by valbok** [comment]
Could you please also check the file by ffplay? if it is playable, and share pls file

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/226

**Comment by valbok** [comment]
Problem was in unknown unsupported streams returned from the demuxer, e.g. data stream dvd_nav_packet
