### ISSUE TITLE
QtAVPlayer Apps fail to terminate after exit signal is called

### ISSUE THREAD

**Issue by awesomeerictech** [valbok/QtAVPlayer#227]
The apps on desktop and android won't close on exit , looks like the process still runs, attempting to kill it results to a crash

**Comment by valbok** [comment]
Windows?

**Comment by awesomeerictech** [comment]
android and linux , for rtmp (s) streams

**Comment by awesomeerictech** [comment]
This issue has nothing to do with QtAVPlayer , so closing it is tenable.
