### ISSUE TITLE
ffmpeg5

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#236]

**Comment by awesomeerictech** [comment]
i have been using ffmpeg 5 with qtavplayer

**Comment by valbok** [comment]
super!

**Comment by valbok** [comment]
is it macos?

**Comment by awesomeerictech** [comment]
android,linux and windows

**Comment by awesomeerictech** [comment]
you can try it out on Mac

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/runs/5570895838?check_suite_focus=true
there is a version in macos build and it shows ffmpeg 5,
exellent.
