### ISSUE TITLE
Aspect ration issue with widgets

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#241]
https://github.com/bavc/qctools/issues/724

**Comment by valbok** [comment]
checked on linux, and not reproducible.

**Comment by dericed** [comment]
i pasted another example at https://github.com/bavc/qctools/issues/724#issuecomment-1164770971.

**Comment by valbok** [comment]
https://github.com/bavc/qctools/blob/main/Source/GUI/player.cpp#L655
