### ISSUE TITLE
Unable to play media on Qt6.3

### ISSUE THREAD

**Issue by AndTessitore** [valbok/QtAVPlayer#255]
I followed your example code but seems the media won't start. This is what I made:
```
QVideoWidget w(baseWidget);
w.show();

QAVPlayer p;
QAVAudioOutput audioOutput;
connect(&p, &QAVPlayer::audioFrame, [&audioOutput](const QAVAudioFrame& frame) {
	qDebug() << "AudioFrame";
	audioOutput.play(frame); 
	});
connect(&p, &QAVPlayer::videoFrame, [&](const QAVVideoFrame& frame) {
	qDebug() << "VideoFrame";
	QVideoFrame videoFrame = frame.convertTo(AV_PIX_FMT_RGB32);
	w.videoSink()->setVideoFrame(videoFrame);
});

p.setSource("PATH-TO-VIDEO");
p.play();
```

At least I expect to see debug messages, but this is the only output:
```
Debug vp9 : supported hardware device contexts:
Debug     dxva2
Debug     d3d11va
Debug     cuda
Debug Creating hardware device context: d3d11va
Debug Using hardware device context: d3d11va
```

**Comment by valbok** [comment]
Thanks for the issue.
Could you please `          set QT_LOGGING_RULES=qt.QtAVPlayer.debug=true
          set QT_FORCE_STDERR_LOGGING=1
          set QT_ASSUME_STDERR_HAS_CONSOLE=1` and check output?

**Comment by AndTessitore** [comment]
> 

Here the output
```
Debug QAVPlayer::setSource : "PATH-TO-VIDEO"
Debug QAVPlayerPrivate::terminate
Debug QAVPlayerPrivate::wait : false -> true
Debug QAVPlayerPrivate::setPendingMediaStatus : NoMedia -> QList(LoadingMedia)
Debug QAVPlayer::play
Debug QAVPlayerPrivate::setState : StoppedState -> PlayingState
Debug QAVPlayerPrivate::setPendingMediaStatus : NoMedia -> QList(LoadingMedia, PlayingMedia)
Debug QAVPlayerPrivate::wait : true -> false
Debug QAVPlayerPrivate::terminate
Debug QAVPlayerPrivate::setState : PlayingState -> StoppedState
Debug vp9 : supported hardware device contexts:
Debug     dxva2
Debug     d3d11va
Debug     cuda
Debug Creating hardware device context: d3d11va
Debug Using hardware device context: d3d11va
Debug QAVPlayerPrivate::doLoad finished
Debug QAVPlayerPrivate::doDemux finished
Debug QAVPlayerPrivate::doPlayVideo finished
Debug QAVPlayerPrivate::doPlayAudio finished
```

**Comment by valbok** [comment]
QT_AVPLAYER_NO_HWDEVICE=1
to prevent using d3d11va
does it help?

**Comment by valbok** [comment]
can you also check `ffplay url` to make sure that it is playable?

**Comment by AndTessitore** [comment]
> QT_AVPLAYER_NO_HWDEVICE=1 to prevent using d3d11va does it help?

Tested and still no output in console nor in the gui

I alredy tested with ffplay and it works

**Comment by valbok** [comment]
is it only this url? or other files can be played?

**Comment by AndTessitore** [comment]
> is it only this url? or other files can be played?

No file can be played. I tried open different files (audio only, video only) but none has worked

**Comment by awesomeerictech** [comment]
@AndTessitore which operating system are you using and ffmpeg ?

**Comment by awesomeerictech** [comment]
i am using qt 6.3 on Windows,Ubuntu and Android and all is working fine .

**Comment by awesomeerictech** [comment]
Your problem starts here ;
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --disable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220411

**Comment by AndTessitore** [comment]
@awesomeerictech I'm using windows 11, I use FFmpeg with tutorial and works really well so I don't understand where the problem is in the configuration.
Which version do you use?

**Comment by valbok** [comment]
Just checked with clean 6.3.0 and qml_video and widget_video examples work.
Could you check standalone examples/widget_video ?

**Comment by valbok** [comment]
QAVPlayerPrivate::terminate

is called when either new source is applied or the player is being destroyed, could you make sure that you do not destroy the player?

**Comment by AndTessitore** [comment]
> QAVPlayerPrivate::terminate
> 
> is called when either new source is applied or the player is being destroyed, could you make sure that you do not destroy the player?

The solution was so easy that I didn't tried it... creating it as a pointer solved this issue since I create it in a slot function ( i need it to play multiple multimedia at same time). Now it outputs all the messages in the console but if I try to show audio / video frames it crashes

**Comment by AndTessitore** [comment]
> Just checked with clean 6.3.0, Windows 10, mingw-64, and qml_video and widget_video examples work. Could you check standalone examples/widget_video ?
> 
> ```
>   h264 : supported hardware device contexts:
>       dxva2
>       d3d11va
>       cuda
>   Creating hardware device context: d3d11va
>   Using hardware device context: d3d11va
>   Available pixel formats:
>      yuv420p : AVPixelFormat( 0 )
>      cuda : AVPixelFormat( 119 )
>      dxva2_vld : AVPixelFormat( 53 )
>      d3d11va_vld : AVPixelFormat( 118 )
>      d3d11 : AVPixelFormat( 174 )
>   Using hardware decoding in d3d11
> ```

Compiled in a clean project and executed example code  from:
https://github.com/valbok/QtAVPlayer/tree/master/examples/widget_video

It works, so there is something I'm messing with signal and slot in my real project

**Comment by AndTessitore** [comment]
> Just checked with clean 6.3.0, Windows 10, mingw-64, and qml_video and widget_video examples work. Could you check standalone examples/widget_video ?
> 
> ```
>   h264 : supported hardware device contexts:
>       dxva2
>       d3d11va
>       cuda
>   Creating hardware device context: d3d11va
>   Using hardware device context: d3d11va
>   Available pixel formats:
>      yuv420p : AVPixelFormat( 0 )
>      cuda : AVPixelFormat( 119 )
>      dxva2_vld : AVPixelFormat( 53 )
>      d3d11va_vld : AVPixelFormat( 118 )
>      d3d11 : AVPixelFormat( 174 )
>   Using hardware decoding in d3d11
> ```

Compiled in a clean project and executed example code  from:
https://github.com/valbok/QtAVPlayer/tree/master/examples/widget_video

It works, so there is something I'm messing with signal and slot in my real project

**Comment by Wkkkkk** [comment]
> QT_AVPLAYER_NO_HWDEVICE=1
> to prevent using d3d11va
> does it help?

This helped me to play out streams.

**Comment by valbok** [comment]
> This helped me to play out streams. MacOS m1, Qt 6.5, ffmpeg 6.0.

It should work without QT_AVPLAYER_NO_HWDEVICE, could you please confirm that there is no issues with playing ? Especially for MacOS.

**Comment by Wkkkkk** [comment]
It works fine for MacOS without QT_AVPLAYER_NO_HWDEVICE. I forgot to set the CMAKE_LIBRARY_PATH so it compiled but were not able to play out stream. It can be fixed once clean up CMake cache.

Sorry for the false alarm.
