### ISSUE TITLE
not working properly on macOS

### ISSUE THREAD

**Issue by leavelet** [valbok/QtAVPlayer#257]
the video is like this

![Screen Shot 2022-06-05 at 20.16.13.png](https://s2.loli.net/2022/06/05/8KJINP42i3wEpsU.png)

**Comment by leavelet** [comment]
My platform is macOS 12.4, with an m1 pro chip
I confirm this issue is not because of my own code, as I test the same code on a windows machine successfully.

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/issues/220
the same?

**Comment by leavelet** [comment]
> My platform is macOS 12.4, with an m1 pro chip
> 
> I confirm this issue is not because of my own code, as I test the same code on a windows machine successfully.

yes

Sorry for not checking issue list

I am trying to figure out what happened
