### ISSUE TITLE
how to player audio continuously?

### ISSUE THREAD

**Issue by leavelet** [valbok/QtAVPlayer#258]
```c++
    QObject::connect(player, &QAVPlayer::audioFrame, player, [this](const QAVAudioFrame &frame) { this->audioOutput.play(frame); });
    QObject::connect(player, &QAVPlayer::videoFrame, player, [this](const QAVVideoFrame &frame) {
//        QVideoFrame videoFrame = frame.convertTo(AV_PIX_FMT_RGB32);
        this->videoWidget->videoSink()->setVideoFrame(frame);
    });
```

I am using code above to play an video, and I found it consumes a lot of sources and the audio is not so smooth.

Am I getting it right? Are there better ways to player videos?

**Comment by valbok** [comment]
started to work?

**Comment by leavelet** [comment]
When testing on a virtual windows machine it happened. 
It turns out that saving every frame to image when debugging makes player work slow, which causes all the problems above.
But my mac has been "too powerful" to make me ignore the problem, so me thought it was a bug...
