### ISSUE TITLE
Crash when using QAVVideoFrame::map() to get frame data

### ISSUE THREAD

**Issue by LI7XI** [valbok/QtAVPlayer#274]
Hi,
`QAVVideoFrame::map()` causes a crash when called more than once.

Here is the code:

<details>
  <summary>Click me</summary>

[_Copied and slightly modified from qt examples_](https://code.qt.io/cgit/qt/qtbase.git/tree/examples/opengl/textures?h=6.3)

```cpp
#ifndef PLAYER_WIDGET_HPP
#define PLAYER_WIDGET_HPP

#include <QOpenGLWidget>
#include <QOpenGLFunctions>
#include <QOpenGLBuffer>
#include <QVideoFrame>
#include <QtAVPlayer/qavvideoframe.h>

class QAVPlayer;
class QAVAudioOutput;

class QOpenGLShaderProgram;
class QOpenGLTexture;

class PlayerWidget
  : public QOpenGLWidget
  , protected QOpenGLFunctions
{
  Q_OBJECT

private:
  QAVPlayer *mPlayer;
  QAVAudioOutput *mAudioOutput;

  QOpenGLShaderProgram *mShaderProgram;
  QOpenGLTexture *mTexture;
  QOpenGLBuffer mVbo;
  QAVVideoFrame mFrame;

public:
  PlayerWidget(QWidget *parent);
  ~PlayerWidget();

protected:
  void initializeGL() override;
  void paintGL() override;
  void resizeGL(int width, int height) override;
};

#endif // PLAYER_WIDGET_HPP
```

```cpp
#include "player_widget.hpp"

#include <QPainter>
#include <QtAVPlayer/qavplayer.h>
#include <QtAVPlayer/qavvideoframe.h>
#include <QtAVPlayer/qavaudioframe.h>
#include <QtAVPlayer/qavaudiooutput.h>
#include <QDebug>

#include <QOpenGLShaderProgram>
#include <QOpenGLTexture>
#include <QOpenGLPixelTransferOptions>

PlayerWidget::PlayerWidget(QWidget *parent)
  : QOpenGLWidget(parent)
  , mShaderProgram(nullptr)
  , mTexture(nullptr)
{
  mTexture = new QOpenGLTexture(QOpenGLTexture::Target2D);

  QString fn = QFileDialog::getOpenFileName(nullptr, tr("Open File"));

  mPlayer = new QAVPlayer(this);
  mPlayer->setSource(fn);

  mAudioOutput = new QAVAudioOutput(this);
  QObject::connect(mPlayer, &QAVPlayer::audioFrame, [this](const QAVAudioFrame &frame) {
    mAudioOutput->play(frame);
  });

  QObject::connect(mPlayer, &QAVPlayer::videoFrame, [=](const QAVVideoFrame &frame) {
    mFrame = frame.convertTo(AV_PIX_FMT_RGB32);
    this->update();
  });

  mPlayer->play();
  mPlayer->pause();
}

PlayerWidget::~PlayerWidget()
{
  makeCurrent();
  mVbo.destroy();
  if (mTexture)
    delete mTexture;
  if (mShaderProgram)
    delete mShaderProgram;
  doneCurrent();
}

void PlayerWidget::initializeGL()
{
  initializeOpenGLFunctions();
  glClearColor(0.3, 0.1, 0.3, 0.5);

  static const int coords[4][3] = {
    { +1, -1, -1 }, { -1, -1, -1 },
    { -1, +1, -1 }, { +1, +1, -1 }
  };

  QList<GLfloat> vertData;
  for (int j = 0; j < 4; ++j)
  {
    // vertex position
    vertData.append(0.3 * coords[j][0]);
    vertData.append(0.3 * coords[j][1]);
    vertData.append(0.2 * coords[j][2]);
    // texture coordinate
    vertData.append(j == 0 || j == 3);
    vertData.append(j == 0 || j == 1);
  }

  mVbo.setUsagePattern(QOpenGLBuffer::StaticDraw);
  mVbo.create();
  mVbo.bind();
  mVbo.allocate(vertData.constData(), vertData.count() * sizeof(GLfloat));

  glEnable(GL_DEPTH_TEST);
  glEnable(GL_CULL_FACE);

#define PROGRAM_VERTEX_ATTRIBUTE 0
#define PROGRAM_TEXCOORD_ATTRIBUTE 1

  QOpenGLShader *vshader = new QOpenGLShader(QOpenGLShader::Vertex, this);
  const char *vsrc =
    "attribute highp vec4 vertex;\n"
    "attribute mediump vec4 texCoord;\n"
    "varying mediump vec4 texc;\n"
    "uniform mediump mat4 matrix;\n"
    "void main(void)\n"
    "{\n"
    "    gl_Position = matrix * vertex;\n"
    "    texc = texCoord;\n"
    "}\n";
  vshader->compileSourceCode(vsrc);

  QOpenGLShader *fshader = new QOpenGLShader(QOpenGLShader::Fragment, this);
  const char *fsrc =
    "uniform sampler2D texture;\n"
    "varying mediump vec4 texc;\n"
    "void main(void)\n"
    "{\n"
    "    gl_FragColor = texture2D(texture, texc.st);\n"
    "}\n";
  fshader->compileSourceCode(fsrc);

  mShaderProgram = new QOpenGLShaderProgram;
  mShaderProgram->addShader(vshader);
  mShaderProgram->addShader(fshader);
  mShaderProgram->bindAttributeLocation("vertex", PROGRAM_VERTEX_ATTRIBUTE);
  mShaderProgram->bindAttributeLocation("texCoord", PROGRAM_TEXCOORD_ATTRIBUTE);
  mShaderProgram->link();

  mShaderProgram->bind();
  mShaderProgram->setUniformValue("texture", 0);
}

void PlayerWidget::paintGL()
{
  glClearColor(0.3, 0.5, 0.3, 1.0);
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

  if (!mFrame)
    return;

  QMatrix4x4 m;
  m.ortho(-0.5f, +0.5f, +0.5f, -0.5f, 4.0f, 15.0f);
  m.translate(0.0f, 0.0f, -10.0f);
  m.rotate(0 / 16.0f, 1.0f, 0.0f, 0.0f);
  m.rotate(0 / 16.0f, 0.0f, 1.0f, 0.0f);
  m.rotate(0 / 16.0f, 0.0f, 0.0f, 1.0f);

  mShaderProgram->setUniformValue("matrix", m);
  mShaderProgram->enableAttributeArray(PROGRAM_VERTEX_ATTRIBUTE);
  mShaderProgram->enableAttributeArray(PROGRAM_TEXCOORD_ATTRIBUTE);
  mShaderProgram->setAttributeBuffer(PROGRAM_VERTEX_ATTRIBUTE, GL_FLOAT, 0, 3, 5 * sizeof(GLfloat));
  mShaderProgram->setAttributeBuffer(PROGRAM_TEXCOORD_ATTRIBUTE, GL_FLOAT, 3 * sizeof(GLfloat), 2, 5 * sizeof(GLfloat));

  auto md = mFrame.map();
  if (md.format != AV_PIX_FMT_NONE)
  {
    QImage img(md.data[0], mFrame.size().width(), mFrame.size().height(),
      md.bytesPerLine[0], QImage::Format_RGBA8888_Premultiplied);
    img.rgbSwap();

    mTexture->destroy();
    mTexture->setSize(mFrame.size().width(), mFrame.size().height());
    mTexture->setData(img.mirrored());

    mTexture->create();
    mTexture->bind();
    glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
  }
}

void PlayerWidget::resizeGL(int width, int height)
{
  int side = qMin(width, height);
  glViewport((width - side) / 2, (height - side) / 2, side, side);
}
```

</details>

You can see the first frame, but it crashes on the second frame.
_(Here i used `QImage` because i still don't know how to convert avFrame data to opengl texture :') so i needed something to test mapData with)._

**Comment by valbok** [comment]
thanks, but https://github.com/valbok/QtAVPlayer/pull/266 fixes downloading it twice, and mapping twice should work https://github.com/valbok/QtAVPlayer/pull/267 ?

**Comment by LI7XI** [comment]
I subsect that _maybe_ QImage or opengl itself keeps a refernce to the data so when the data changes or gets deleted a crash occurs?
lemme check real quick..

**Comment by LI7XI** [comment]
>thanks, but https://github.com/valbok/QtAVPlayer/pull/266 fixes downloading it twice, and mapping twice should work https://github.com/valbok/QtAVPlayer/pull/267 ?

It's not the same, here it's like getting the same data twice, but in my example i try to get the next frame data.

**Comment by LI7XI** [comment]
Commenting out these lines stops the crashes:

``` cpp

    // mTexture->destroy();
    // mTexture->setSize(mFrame.size().width(), mFrame.size().height());
    // mTexture->setData(img.mirrored());

    // mTexture->create();
    // mTexture->bind();
    // glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
```

**Comment by LI7XI** [comment]
I found a workaround! :D 

Using the original example, simply use `Qt::QueuedConnection` for the update signal like so:

```cpp
  QObject::connect(mPlayer, &QAVPlayer::videoFrame, this, [=](const QAVVideoFrame &frame) {
    mFrame = frame.convertTo(AV_PIX_FMT_RGB32);
    this->update();
  }, Qt::QueuedConnection);
```

Not sure if that's a good solution but the crashes are gone which is good.

**Comment by valbok** [comment]
great, will check DirectAccess and mapping, maybe something is missing there.

Since you use direct data  `mTexture->setData(img.mirrored());` you could convert to BGR32 data once and pass it here.

and yes `frame.convertTo(AV_PIX_FMT_RGB32);` is expensive operation.

**Comment by valbok** [comment]
Also interesting but seems it might be possible to convert ID3D11Texture2D to opengl textures

**Comment by LI7XI** [comment]
Hello, sorry for late response

>and yes frame.convertTo(AV_PIX_FMT_RGB32); is expensive operation.

yeah i noticed, it would be amazing if i could use the native format directly for drawing.

>Also you still did not provide stacktrace for the crash. Is it while using map()? or is it about mutex or what?

i'm sorry i don't know if i can help here, i'm using release config for everything and `qDebug()` is my only source of information '~'
The example i provided above crashes once i call play() after getting the first frame. I don't get any other output.

>Also interesting but seems it might be possible to convert ID3D11Texture2D to opengl textures

That's great news! :D can i implement this on my own or does it require a change in the library itself?

**Comment by LI7XI** [comment]
@valbok any updates?

**Comment by valbok** [comment]
Sorry for delays.
1. It should not crash on multiple maps or DirectAccess. https://github.com/valbok/QtAVPlayer/pull/266 should have fixed that, but need to recheck
2. About converting D3D11 to OpenGL -> need to fix QAVHWDevice_D3D11 to add video buffer with converting. https://github.com/wang-bin/QtAV/blob/master/src/directx/SurfaceInteropD3D9GL.cpp there is an example, but I never tested this.

**Comment by LI7XI** [comment]
>About converting D3D11 to OpenGL -> need to fix QAVHWDevice_D3D11 to add video buffer with converting. - e.g how it is done in VideoBuffer_VDPAU_GLX and https://github.com/wang-bin/QtAV/blob/master/src/directx/SurfaceInteropD3D9GL.cpp there is an example, but I never tested this.

Thanks for pointing out, i'll look into this.

About the crashes, using `Qt::QueuedConnection` seems to fix the issue.
Thanks for your help! :)

**Comment by valbok** [comment]
@LI7XI  Just checked double mapping on Windows with d3d11 -> no crashes
Could you please check if it crashes for you?
```    QObject::connect(&p, &QAVPlayer::videoFrame, &p, [&](const QAVVideoFrame &frame) {
        auto md = frame.map();
        md = frame.map();
    }, Qt::DirectConnection);
```

**Comment by LI7XI** [comment]
No crashes here too, the problem is not double mapping.

Here is what i think (take with grain of salt):

Lets say you call map in that connection, then you use the mapped data in another function, but meanwhile your function is using it, a new frame arrives, and it overrides/changes/delete the previous mapped data while it's being used, this _may_ cause a crash, because i assume ffmpeg is running on a separate thread?

But when using `Qt::QueuedConnection`, you get a new frame -> map -> tell qt to wait -> use the mapped data -> then receive the following frame

I hope that makes sense.

---

If you can try the example i provided you can clearly see the crash.
