### ISSUE TITLE
Error compiling for Android on MacOS, Qt 6.4.3

### ISSUE THREAD

**Issue by geminixdev** [valbok/QtAVPlayer#299]
Fresh download, unchanged, compiling for arm64-v8a, then error at linking. I assume  because the android ffmpeg libraries are not OK. Which is a question which possibly could get avoided if QtAVPlayer could get configured to use the ffmpeg provided with Qt 6.4.3 and later. See #276

The environment:

```
export AVPLAYER_ANDROID_LIB_ARMEABI_V8A=/Users/myname/Projects/QtAVPlayer.android/ffmpeg/arm64-v8a/lib
export AVPLAYER_ANDROID_LIB_X86=/Users/myname/Projects/QtAVPlayer.android/ffmpeg/x86/lib
export AVPLAYER_ANDROID_LIB_X86_64=/Users/myname/Projects/QtAVPlayer.android/ffmpeg/x86_64/lib
export CPLUS_INCLUDE_PATH=/Users/myname/Projects/QtAVPlayer.android/ffmpeg/arm64-v8a/include:$CPLUS_INCLUDE_PATH
export ANDROID_NDK_ROOT=/Users/myname/Development/android-sdk-macosx/ndk/23.1.7779620
```

qmake:

```
~/Qt/6.4.3/android_arm64_v8a/bin/qmake
```

compiling (with make -j8) goes through without error, until linking:

```
/Users/myname/Development/android-sdk-macosx/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -target aarch64-linux-android23 -fno-limit-debug-info -Wl,--no-undefined -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,-z,noexecstack -shared -Wl,-soname,libQt6AVPlayer_arm64-v8a.so -o libQt6AVPlayer_arm64-v8a.so .obj/qavaudiooutput.o .obj/qavplayer.o .obj/qavcodec.o .obj/qavframecodec.o .obj/qavaudiocodec.o .obj/qavvideocodec.o .obj/qavsubtitlecodec.o .obj/qavdemuxer.o .obj/qavpacket.o .obj/qavframe.o .obj/qavstreamframe.o .obj/qavvideoframe.o .obj/qavaudioframe.o .obj/qavsubtitleframe.o .obj/qavvideobuffer_cpu.o .obj/qavvideobuffer_gpu.o .obj/qavfilter.o .obj/qavvideofilter.o .obj/qavaudiofilter.o .obj/qavfiltergraph.o .obj/qavinoutfilter.o .obj/qavvideoinputfilter.o .obj/qavaudioinputfilter.o .obj/qavvideooutputfilter.o .obj/qavaudiooutputfilter.o .obj/qaviodevice.o .obj/qavstream.o .obj/qavfilters.o .obj/qavhwdevice_mediacodec.o .obj/moc_qavplayer.o  -L/Users/myname/Projects/QtAVPlayer.android/ffmpeg/arm64-v8a/lib -lavcodec -lavformat -lswscale -lavutil -lswresample /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Multimedia_arm64-v8a.so /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Gui_arm64-v8a.so -lEGL /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Network_arm64-v8a.so /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Concurrent_arm64-v8a.so /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Core_arm64-v8a.so -llog -pthread -lGLESv2 /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Gui_arm64-v8a.so -lEGL /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Core_arm64-v8a.so -llog -pthread -lGLESv2  -llog -lz -lm -ldl -lc 
ld: error: undefined symbol: avdevice_register_all
>>> referenced by qavdemuxer.cpp:110
>>>               .obj/qavdemuxer.o:(QAVDemuxer::QAVDemuxer(QObject*))

ld: error: undefined symbol: av_buffersrc_add_frame_flags
>>> referenced by qavvideofilter.cpp:68
>>>               .obj/qavvideofilter.o:(QAVVideoFilter::write(QAVFrame const&))
>>> referenced by qavaudiofilter.cpp:61
>>>               .obj/qavaudiofilter.o:(QAVAudioFilter::write(QAVFrame const&))

ld: error: undefined symbol: av_buffersink_get_frame_flags
>>> referenced by qavvideofilter.cpp:94
>>>               .obj/qavvideofilter.o:(QAVVideoFilter::read(QAVFrame&))
>>> referenced by qavaudiofilter.cpp:86
>>>               .obj/qavaudiofilter.o:(QAVAudioFilter::read(QAVFrame&))

ld: error: undefined symbol: av_buffersink_get_frame_rate
>>> referenced by qavvideofilter.cpp:100
>>>               .obj/qavvideofilter.o:(QAVVideoFilter::read(QAVFrame&))

ld: error: undefined symbol: av_buffersink_get_time_base
>>> referenced by qavvideofilter.cpp:101
>>>               .obj/qavvideofilter.o:(QAVVideoFilter::read(QAVFrame&))
>>> referenced by qavaudiofilter.cpp:92
>>>               .obj/qavaudiofilter.o:(QAVAudioFilter::read(QAVFrame&))

ld: error: undefined symbol: av_buffersrc_add_frame
>>> referenced by qavvideofilter.cpp:127
>>>               .obj/qavvideofilter.o:(QAVVideoFilter::flush())
>>> referenced by qavaudiofilter.cpp:118
>>>               .obj/qavaudiofilter.o:(QAVAudioFilter::flush())

ld: error: undefined symbol: avfilter_graph_free
>>> referenced by qavfiltergraph.cpp:51
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::~QAVFilterGraph())
>>> referenced by qavfiltergraph.cpp:51
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::~QAVFilterGraph())
>>> referenced by qavfiltergraph.cpp:60
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::parse(QString const&))

ld: error: undefined symbol: avfilter_inout_free
>>> referenced by qavfiltergraph.cpp:52
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::~QAVFilterGraph())
>>> referenced by qavfiltergraph.cpp:53
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::~QAVFilterGraph())
>>> referenced by qavfiltergraph.cpp:52
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::~QAVFilterGraph())
>>> referenced 3 more times

ld: error: undefined symbol: avfilter_graph_alloc
>>> referenced by qavfiltergraph.cpp:63
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::parse(QString const&))

ld: error: undefined symbol: avfilter_graph_parse2
>>> referenced by qavfiltergraph.cpp:64
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::parse(QString const&))

ld: error: undefined symbol: avfilter_pad_get_type
>>> referenced by qavfiltergraph.cpp:91
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::apply(QAVFrame const&))
>>> referenced by qavfiltergraph.cpp:116
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::apply(QAVFrame const&))

ld: error: undefined symbol: avfilter_graph_config
>>> referenced by qavfiltergraph.cpp:146
>>>               .obj/qavfiltergraph.o:(QAVFilterGraph::config())

ld: error: undefined symbol: avfilter_get_by_name
>>> referenced by qavvideoinputfilter.cpp:97
>>>               .obj/qavvideoinputfilter.o:(QAVVideoInputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced by qavaudioinputfilter.cpp:96
>>>               .obj/qavaudioinputfilter.o:(QAVAudioInputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced by qavvideooutputfilter.cpp:34
>>>               .obj/qavvideooutputfilter.o:(QAVVideoOutputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced 1 more times

ld: error: undefined symbol: avfilter_graph_create_filter
>>> referenced by qavvideoinputfilter.cpp:96
>>>               .obj/qavvideoinputfilter.o:(QAVVideoInputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced by qavaudioinputfilter.cpp:95
>>>               .obj/qavaudioinputfilter.o:(QAVAudioInputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced by qavvideooutputfilter.cpp:33
>>>               .obj/qavvideooutputfilter.o:(QAVVideoOutputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced 1 more times

ld: error: undefined symbol: avfilter_link
>>> referenced by qavvideoinputfilter.cpp:102
>>>               .obj/qavvideoinputfilter.o:(QAVVideoInputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced by qavaudioinputfilter.cpp:101
>>>               .obj/qavaudioinputfilter.o:(QAVAudioInputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced by qavvideooutputfilter.cpp:39
>>>               .obj/qavvideooutputfilter.o:(QAVVideoOutputFilter::configure(AVFilterGraph*, AVFilterInOut*))
>>> referenced 1 more times
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../lib/libQt6AVPlayer_arm64-v8a.so] Error 1
make[1]: *** [sub-QtAVPlayer-make_first] Error 2
make: *** [sub-src-make_first] Error 2

```

May be a hint as to where to get the prebuilt Android ffmpeg libraries might be sufficient to solve this, unless there is a step I was missing.

At least when developing for Android or iOS it could be very helpful if QtAVPlayer could get configured to use the ffmpeg provided with Qt 6.4.3 and later, as discussed in #276 

Although I have a lot of experience with ffmpeg, including compiling it on Mac and Linux, I struggle with doing so for Android and iOS. Therefore I propose to add a link or hint to the build instructions to point to working (and recent) prebuilt libraries or to good instructions.

**Comment by geminixdev** [comment]
The link command line above, after which the errors start, is not easy to read due to it's length, therefore here again but broken down in shorter lines:

```
/Users/myname/Development/android-sdk-macosx/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ 
-target aarch64-linux-android23 -fno-limit-debug-info -Wl,--no-undefined -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,-z,noexecstack 
-shared -Wl,-soname,libQt6AVPlayer_arm64-v8a.so -o libQt6AVPlayer_arm64-v8a.so .obj/qavaudiooutput.o .obj/qavplayer.o 
.obj/qavcodec.o .obj/qavframecodec.o .obj/qavaudiocodec.o .obj/qavvideocodec.o .obj/qavsubtitlecodec.o .obj/qavdemuxer.o 
.obj/qavpacket.o .obj/qavframe.o .obj/qavstreamframe.o .obj/qavvideoframe.o .obj/qavaudioframe.o .obj/qavsubtitleframe.o 
.obj/qavvideobuffer_cpu.o .obj/qavvideobuffer_gpu.o .obj/qavfilter.o .obj/qavvideofilter.o .obj/qavaudiofilter.o 
.obj/qavfiltergraph.o .obj/qavinoutfilter.o .obj/qavvideoinputfilter.o .obj/qavaudioinputfilter.o .obj/qavvideooutputfilter.o 
.obj/qavaudiooutputfilter.o .obj/qaviodevice.o .obj/qavstream.o .obj/qavfilters.o .obj/qavhwdevice_mediacodec.o 
.obj/moc_qavplayer.o  -L/Users/myname/Projects/QtAVPlayer.android/ffmpeg/arm64-v8a/lib -lavcodec -lavformat -lswscale 
-lavutil -lswresample /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Multimedia_arm64-v8a.so 
/Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Gui_arm64-v8a.so -lEGL /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Network_arm64-v8a.so 
/Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Concurrent_arm64-v8a.so /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Core_arm64-v8a.so 
-llog -pthread -lGLESv2 /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Gui_arm64-v8a.so 
-lEGL /Users/myname/Qt/6.4.3/android_arm64_v8a/lib/libQt6Core_arm64-v8a.so -llog -pthread -lGLESv2  -llog -lz -lm -ldl -lc 
```

**Comment by geminixdev** [comment]
Or is the problem that I try this on a M1 Mac with Ventura?

**Comment by valbok** [comment]
thanks, it might be also possible need to fix libs for the linker, sequence, or missing. Or is it ok for prev versions?

**Comment by geminixdev** [comment]
I have not tried any different versions yet.
On the same Mac M1 I can develop and install Android apps using Qt 6.4.3 with QTMM. 
This is the first time I try QtAVPlayer for Android, because I lost patience with QTMM. 
QtAVPlayer for Mac, I tried that, the QML example, it runs fine. (It's what I need on Android and iOS.)

**Comment by geminixdev** [comment]
You mention ".. linker, sequence ..": Originally you have in the QtAVPlayer.pro the order, first 
```
    LIBS += -lavcodec -lavformat -lswscale -lavutil -lswresample
```
and then
```
    equals(ANDROID_TARGET_ARCH, arm64-v8a): \
        LIBS += -L$$(AVPLAYER_ANDROID_LIB_ARMEABI_V8A)

```
I reversed that, but that did not change the error.

**Comment by geminixdev** [comment]
_"...or missing"_ that was it.
It links and installs QtAVPlayer to 'Qt/6.4.3/android_arm64_v8a' now , after adding **lavdevice** and **lavfilter** :

```
    LIBS +=  -lavdevice -lavformat -lavutil -lavcodec -lavfilter -lswscale  -lswresample 
```

**Comment by geminixdev** [comment]
So the QtAVPlayer.pro in src/QtAVPlayer/QtAVPlayer.pro needs to get modified as above, the working line is 
```
    LIBS +=  -lavdevice -lavformat -lavutil -lavcodec -lavfilter -lswscale  -lswresample 
```

Thanks and thanks for this great project!

**Comment by geminixdev** [comment]
The example qml_video compiles with it and installs on a device (Samsung S10+ Android 12). It plays http streams and uses mediacodec, which, if I understood correctly, means hardware decoding:

```
D libqml_video_arm64-v8a.so: h264_mediacodec : supported hardware device contexts:
D libqml_video_arm64-v8a.so:     mediacodec
D libqml_video_arm64-v8a.so: Creating hardware device context: mediacodec
D libqml_video_arm64-v8a.so: Using hardware device context: mediacodec
...
D libqml_video_arm64-v8a.so: FFmpeg: [h264_mediacodec @ 0x72aee4a010] Output MediaFormat changed to {crop-right=1279, vendor.rtc-ext-dec-caps-vt-driver-version.number=180315, vendor.rtc-ext-dec-low-latency.enable=0, color-format=21, slice-height=720, image-data=java.nio.HeapByteBuffer[pos=0 lim=104 cap=104], mime=video/raw, vendor.sec-ext-dec-compressed-color-format=0, stride=1280, color-standard=1, color-transfer=3, crop-bottom=719, crop-left=0, width=1280, color-range=2, crop-top=0, height=720}
04-05 22:05:23.221 18525 18607 D libqml_video_arm64-v8a.so:
D libqml_video_arm64-v8a.so: FFmpeg: [h264_mediacodec @ 0x72aee4a010] Output crop parameters top=0 bottom=719 left=0 right=1279, resulting dimensions width=1280 height=720
04-05 22:05:23.221 18525 18607 D libqml_video_arm64-v8a.so:
```

Nevertheless, the videos play much too slow, only about 10 fps. (The input video itself is 25 fps.) I assume that the moving of the decoded images to the display is too slow, possibly not accelerated. What to do to speed it up?

**Comment by valbok** [comment]
>It plays http streams

what about some video files? it has old code and codec h264_mediacodec was hardcoded

**Comment by geminixdev** [comment]
With the file used in the example, "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4", it is the same, far too slow.

All streams I'm testing are h264, thus h264_mediacodec sounds ok. I don't know if there is a better alternative.

**Comment by geminixdev** [comment]
Possibly an audio issue, slowing down all? 
There are audio errors logged:
```
W AudioCapabilities: Unsupported mime audio/x-ape
W AudioCapabilities: Unsupported mime audio/x-ima
W AudioCapabilities: Unsupported mime audio/mpeg-L1
W AudioCapabilities: Unsupported mime audio/mpeg-L2
W VideoCapabilities: Unsupported mime video/mp43
W VideoCapabilities: Unsupported mime video/wvc1
W VideoCapabilities: Unsupported mime video/x-ms-wmv
W AudioCapabilities: Unsupported mime audio/x-ms-wma
W VideoCapabilities: Unsupported mime video/x-ms-wmv7
W VideoCapabilities: Unsupported mime video/x-ms-wmv8
I ACodec  :  [] Now uninitialized
I ACodec  : [] onAllocateComponent
I OMXClient: IOmx service obtained
I ACodec  : [OMX.Exynos.avc.dec] Now Loaded
D MediaCodec: flushMediametrics
I ACodec  : app-pid(23897)
W ACodec  : [OMX.Exynos.avc.dec] setting HDRStaticInfo failed even though codec advertises support
W ACodec  : [OMX.Exynos.avc.dec] getting HDRStaticInfo failed even though codec advertises support
I ACodec  : [OMX.Exynos.avc.dec] Now Loaded->Idle
I MediaCodec: setCodecState state(0), called in 6
```
and 
```
I ACodec  : [OMX.Exynos.avc.dec] Now Idle->Executing
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
I ACodec  : [OMX.Exynos.avc.dec] calling emptyBuffer 1 w/ codec specific data, size : 25
I ACodec  : [OMX.Exynos.avc.dec] calling emptyBuffer 2 w/ codec specific data, size : 8
W QtAudioDeviceManager: Built in Earpiece may not work when Wired Headphones are connected
D project.exampl: PlayerBase::PlayerBase()
D project.exampl: TrackPlayerBase::TrackPlayerBase()
I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
W ACodec  : [OMX.Exynos.avc.dec] getting HDRStaticInfo failed even though codec advertises support
I ACodec  : [OMX.Exynos.avc.dec] Now handling output port settings change
W AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
W AHierarchicalStateMachine:   int32_t type = 0
W AHierarchicalStateMachine:   int32_t event = 3
W AHierarchicalStateMachine:   int32_t data1 = 1
W AHierarchicalStateMachine:   int32_t data2 = 117440527
W AHierarchicalStateMachine: } unhandled in root state.
D AudioTrack: createTrack_l(114): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 882
I AudioTrack: Need throttle time for OpenSLES player
E android.media.AudioTrack: getMinBufferSize(): Invalid audio format.
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
W ACodec  : [OMX.Exynos.avc.dec] getting HDRStaticInfo failed even though codec advertises support
I ACodec  : [OMX.Exynos.avc.dec] OMX_EventPortSettingsChanged 0x7f030010
```

**Comment by geminixdev** [comment]
The audio seems to be playing with a very incorrect samplerate. But I don't see where I can check or set that at QAVAudioOutput.

**Comment by geminixdev** [comment]
The audioframe connect is triggered precisely every 23 msec. I think there it's only the wrong format/samplerate making problems. 

The videoframe connect however is triggered in bursts, in groups of 5 - 6 videoframes.
The first takes a long time, then 4 frames very fast, then the 6th frame a little slower. Example: 

```
 Video  341 ms, PTS 14512.5 duration 40 ms
 Video  2 ms, PTS 14512.5 duration 40 ms
 Video  2 ms, PTS 14512.6 duration 40 ms
 Video  3 ms, PTS 14512.6 duration 40 ms
 Video  33 ms, PTS 14512.6 duration 40 ms
 Video  40 ms, PTS 14512.7 duration 40 ms

 Video  339 ms, PTS 14512.9 duration 40 ms
 Video  2 ms, PTS 14512.9 duration 40 ms
 Video  3 ms, PTS 14513 duration 40 ms
 Video  4 ms, PTS 14513 duration 40 ms
 Video  16 ms, PTS 14513 duration 40 ms
...
```
It seems that I have to add the code to time the videoframe display, so that (in this 25 fps case) every 40 ms a videoframe will get displayed? This is not handled by QtAVPlayer? 

If so, that is OK, I can do that, I even like that!
I just want to sure that I understand correctly and this is the way to do it. Please confirm or correct.

**Comment by geminixdev** [comment]
> The audio seems to be playing with a very incorrect samplerate. But I don't see where I can check or set that at QAVAudioOutput.

it seems to be hardcoded to samplerate 48000. 

48000 streams have the audio playing ok. 
44100 streams have stuttering audio.

How to set it, ideally using the values of the incoming stream?

**Comment by valbok** [comment]
> Possibly an audio issue, slowing down all? There are audio errors logged:
It is possible to avoid decoding audio frames, but setAudioStreams({}); -- no audio frames should be decoded and sent. But yes, if there is pts mistake, video can try to chase the pts of audio stream, but it is very unlikely that it is slow because of audio.

**Comment by valbok** [comment]
> All streams I'm testing are h264, thus h264_mediacodec sounds ok. I don't know if there is a better alternative.

When tested last time (long time ago against 5.15), it was ok, gonna try again.

**Comment by valbok** [comment]
> The audio seems to be playing with a very incorrect samplerate. But I don't see where I can check or set that at QAVAudioOutput.

QAVAudioFrame::format() what shows? It might have some bugs, since not all formats have been tested,

**Comment by geminixdev** [comment]
> Possibly an audio issue, slowing down all? There are audio errors logged:
> It is possible to avoid decoding audio frames, but setAudioStreams({}); -- no audio frames should be decoded and sent. But yes, if there is pts mistake, video can try to chase the pts of audio stream, but it is very unlikely that it is slow because of audio.

I tried `p.setAudioStreams({})` before and after p.setSource(file) and p.play() (_in main.cpp of the qml example_), but audio still gets decoded.

Also samplerate 48000 audio plays, so it seems to be not an audio issue.

Looking at the PTS values of the video and audio frames, it does not look as if video waits for audio.

I tested also with not playing audio, skipping the `audioOutput.play(frame);` call, but still too slow.
I tested with dropping every second videoframe before displaying, by skipping `videoSurface->setVideoFrame(videoFrame);` for every second videoframe, but still too slow.

So by not playing audio or showing less video it doesn't change anything. This is looks to me as if the slowness is on the decoding side, not the displaying side.

**Comment by valbok** [comment]
>I tried p.setAudioStreams({}) before and after p.setSource(file) and p.play() (in main.cpp of the qml example), but audio still gets decoded.

yep, you need to do when LoadedMedia, when all streams available, but seems needs to be fixed to allow to clear streams at any time

**Comment by valbok** [comment]
>This is looks to me as if the slowness is on the decoding side, not the displaying side.
yep, this is the first idea. QML example has fps shown, you can check how many frames received for rendering. and fps of qml scene updates.

**Comment by geminixdev** [comment]
Testing with QT_AVPLAYER_NO_HWDEVICE : 
```
    qputenv("QT_AVPLAYER_NO_HWDEVICE", "1");
    QAVPlayer p;
```
It seems to not make any difference, possibly even a little slower, if anything.

**Comment by geminixdev** [comment]
> This is looks to me as if the slowness is on the decoding side, not the displaying side.
> yep, this is the first idea. QML example has fps shown, you can check how many frames received for rendering. and fps of qml scene updates.

Indeed, fps values shown are around 8-10 only, while the videos are 25.

**Comment by valbok** [comment]
> > This is looks to me as if the slowness is on the decoding side, not the displaying side.
> > yep, this is the first idea. QML example has fps shown, you can check how many frames received for rendering. and fps of qml scene updates.
> 
> Indeed, fps values shown are around 8-10 only, while the videos are 25.

qml and video fps the same? or qml is higher?

**Comment by geminixdev** [comment]
> around 8-10

sometimes ist shows 2-3 fps only

**Comment by geminixdev** [comment]
> > I tried p.setAudioStreams({}) before and after p.setSource(file) and p.play() (in main.cpp of the qml example), but audio still gets decoded.
> 
> yep, you need to do when LoadedMedia, when all streams available, but seems needs to be fixed to allow to clear streams at any time

OK, works, with p.setAudioStreams({}) in the LoadedMedia event handler, then audio is not decoded. 
It does not influence the slowness though, unfortunately.

**Comment by geminixdev** [comment]
> > > This is looks to me as if the slowness is on the decoding side, not the displaying side.
> > > yep, this is the first idea. QML example has fps shown, you can check how many frames received for rendering. and fps of qml scene updates.
> > 
> > 
> > Indeed, fps values shown are around 8-10 only, while the videos are 25.
> 
> qml and video fps the same? or qml is higher?

QML is usually 1 or 2 higher.

Currently, after running more than 5 minutes, it shows 

- Video fps 13, 
- QML fps 14.

Audio (48000) sounds OK, video is unwatchable, broken.

**Comment by valbok** [comment]
> Video fps 13, QML fps 14.

if qml is slow, means that CPU is not enough, update events are struggling to receive, you can try avoid rendering video, and just render qml fps (or any dummy timer), and see if the fps will be higher?

**Comment by geminixdev** [comment]
> > Video fps 13, QML fps 14.
> 
> if qml is slow, means that CPU is not enough, update events are struggling to receive, you can try avoid rendering video, and just render qml fps (or any dummy timer), and see if the fps will be higher?

when commenting out `videoSurface->setVideoFrame(videoFrame);` then we get perfect Audio and 

Video fps 13,
QML fps 1.

Possibly because _qml fps_ depends on the `QQuickView::afterRendering` event and without showing the video image there is nothing to render. Nevertheless video fps does not go up.

**Comment by valbok** [comment]
> Nevertheless video fps does not go up.
this is why asked to add a timer in qml to update a text f.e. to trigger updates

**Comment by geminixdev** [comment]
> > > Video fps 13, QML fps 14.
> > 
> > 
> > if qml is slow, means that CPU is not enough, update events are struggling to receive, you can try avoid rendering video, and just render qml fps (or any dummy timer), and see if the fps will be higher?
> 
> when commenting out `videoSurface->setVideoFrame(videoFrame);` then we get perfect Audio and
> 
> Video fps 13, QML fps 1.
> 
> Possibly because _qml fps_ depends on the `QQuickView::afterRendering` event and without showing the video image there is nothing to render. Nevertheless video fps does not go up.

Please not that the same device, Samsung S10+, has no performance problem at all problem with a heavy QML application with QTMM, playing HLS streams.

**Comment by valbok** [comment]
or you are right that qml update event is triggered only by video, which is struggling to decode, so qml fps suddenly is the same as video.

**Comment by geminixdev** [comment]
After it was clear that video decoding might be the problem, I thought it might be good to try a different set of ffmpeg libraries. I had used the ones from ffmpegKit, but had a funny feeling with them.

Now I have built new ffmeg 5.1.3 libraries using https://github.com/Javernaut/ffmpeg-android-maker and surprise surprise, it works, great and fast, **Video 24 fps, QML 24 fps, audio and video quality perfect!!!**

Thanks for your help, it allowed me to exclude step by step other possibilities, until the problem was found.

You can't imagine how exited I am to finally see a way to kick out QTMM not only on Linux/Mac/Windows, where I work with ffmpeg directly forever, but now also on Android, and after that hopefully on iOS!  :) :) :)

**Comment by valbok** [comment]
>Now I have built new ffmeg 5.1.3 libraries using https://github.com/Javernaut/ffmpeg-android-maker and surprise surprise, it works, great and fast, Video 24 fps, QML 24 fps, audio and video quality perfect!!!

Awesome that you tried this, not obvious to change ffmpeg ? *-)

**Comment by valbok** [comment]
closing since it already compiles
