### ISSUE TITLE
Compiling QtAVPlayer for iOS - avdevice and missing multimedia error

### ISSUE THREAD

**Issue by geminixdev** [valbok/QtAVPlayer#330]
From the Readme:

> macOS and iOS:
>
> ```
> $ export FFMPEG_ROOT=/usr/local/Cellar/ffmpeg/4.3_1
> $ export LIBRARY_PATH=$FFMPEG_ROOT/lib:$LIBRARY_PATH
> $ export CPLUS_INCLUDE_PATH=$FFMPEG_ROOT/include:$CPLUS_INCLUDE_PATH
> $ cd QtAVPlayer && qmake && make -j8    
> ```

The FFMPEG_ROOT shown here, '/usr/local/Cellar/ffmpeg/4.3_1', looks to me like where homebrew installs the libraries for MacOS. I don't think they can get used for iOS. If they can, or if there is a way to install the ffmpeg libraries which can get used for iOS using brew or similar, can you please explain?

When looking for prebuilt ffmpeg libraries for iOS, all I could find are either 'Frameworks', or they don't contain libavdevice (for example the prebuilt libraries from https://github.com/wang-bin/avbuild). 

When I try to use them to complile QtAVPlayer I get the error that **libavdevice** is not found (also when I make sure that libavdevice is not specified in the .pro file).

Using the build script at https://github.com/wang-bin/avbuild I tried to build the ffmpeg libraries including avdevice. In order to do so I had to edit the script, it was built in there to disable avdevice when building for iOS. 

Therefore I assume that there is a reason for that. Does QtAVPlayer need that dependency on avdevice when building for iOS?

When I try to compile QtAVplayer for iOS with these libraries I just made, include libavdevice, I get the error

```
Project ERROR: Could not find feature multimedia.
make[1]: *** [sub-QtAVPlayer-make_first] Error 3
make: *** [sub-src-make_first] Error 2
```

How to fix?

**Comment by valbok** [comment]
Great you started iOS =)
> Project ERROR: Could not find feature multimedia.
not clean build? It should build if there is no QtMM

**Comment by geminixdev** [comment]
> Great you started iOS =)
> 
> > Project ERROR: Could not find feature multimedia.
> not clean build? It should build if there is no QtMM

QtMM should be installed. the Qt ios Folder also shows Qt Multimedia files.
<img width="509" alt="Qt 6 4 3 installation" src="https://user-images.githubusercontent.com/125993656/236479433-3affe8a7-00c2-4472-81d0-9cc527ab70a4.png">

**Comment by valbok** [comment]
you need to clear any qmake files, git clean -dfx; qmake

**Comment by geminixdev** [comment]
> you need to clear any qmake files, git clean -dfx; qmake
> 
> ```
> Qt AVPlayer:
>    Qt Multimedia .......................... yes
> ```

Thanks, the clean install did the trick. Now QtAVPlayer compiled without any error.

**Comment by valbok** [comment]
Is it still relevant?

**Comment by geminixdev** [comment]
> Is it still relevant?

Yes, still relevant.
Sorry, I was occupied elsewhere, but have to come back to this very soon.

**Comment by geminixdev** [comment]
> Still experiencing any issues ?

I didn’t get to this yet. However now, with Android working sufficiently well now (see #322) now it’s iOS time again.

**Comment by geminixdev** [comment]
Compiling the App for iOS resulted in many link errors, due to the unavailability of many libraries under iOS. Thus the ffmpeg libraries need to be compiled with disabling as much as possible, for example

 ```
  --disable-libxcb # gets rid of libxcb* dependencies
  --disable-xlib # gets rid of libX* dependencies
  --disable-lzma # gets rid of liblzma dependency
  --disable-vaapi # gets rid of libva dependency
  --disable-alsa # gets rid of libasound dependency
```

With these dependencies removed the App compiled and could get installed on iOS devices.

**Comment by geminixdev** [comment]
The App compiled using QtCreator (Qt 6.4.3), Xcode and QtAVPlayer for MacOS, iOS-Simulator and iOS:

Testing on MacOS and iOS-Simulator:
- all works perfectly, playing is smooth.

Testing on iOS devices:
- very old 12" Pro iPad - Playing stutters, audio and video not smooth.
- iPhone XS and 11ProMax, and iPad pro 11 - playing is smooth and nice, perfect.

BUT

After 10 - 15 minutes the UI freezes. It continues to play, audio plays non stop and perfect - but either no image update or 1 image per minute, while the UI is frozen, does not react. Sometimes it crashes after a while in that state.

This is on real devices only, on Mac or iOS Simulator it plays for hours, no freeze, memory usage stable, CPU low. No reason found yet for that freezing. Also looking at the device system log using Console shows nothing useful.

**Comment by geminixdev** [comment]
The freeze issue (mentioned above) seems to be bug in QtMM, there is a resource leak in videoSink->setVideoFrame() for videotoolbox decoded Frames. 

This issue was about compiling QtAVPlayer for iOS, and that part works fine now. Closing.
