### ISSUE TITLE
Changing player speed does not affect QAVAudioOutput

### ISSUE THREAD

**Issue by J-TAG** [valbok/QtAVPlayer#331]
Hi, Thanks for this great project.

I managed to use QML example in repository to create a simple QML application using Qt 5.15 and ffmpeg 6.0.
Using `QDeclarativeVideoOutput` and `QAVAudioOutput` I can easily play video files using ffmpeg. 
Things like playing video and audio, seeking through video and changing volume works perfectly.
But when I change the speed of `QAVPlayer` using `p.setSpeed(4);` , the video will be speed up, but the audio is not speed up and keeps playing even after pausing or stoping player. I remember few month back this was working correctly but now after I updated the QtAVPlayer, it does not work anymore.

Here is how I'm using `QAVAudioOutput`

```
QAVAudioOutput audioOutput;
QAVPlayer p;
//... other stuff for QAVPlayer
QObject::connect(&p, &QAVPlayer::audioFrame, &p, [&audioOutput](const QAVAudioFrame &frame) { audioOutput.play(frame); });
p.play();
p.setSpeed(2);
```

It seems the problem comes from `qavaudiooutput.cpp`. I'd be happy to help if you need more info or source modification though I know nothing about ffmpeg but I know Qt.

I could test this behavior in Linux and Android build using Qt 5.15 and ffmpeg 6.0, but I'll assume it's the same in other targets also.

Thank you so much.

**Comment by valbok** [comment]
Thanks, it is definitely a regression, since not covered by tests, just missed.
https://github.com/valbok/QtAVPlayer/pull/332 could you please check this?

**Comment by J-TAG** [comment]
Thank you. I'll check and report.

**Comment by J-TAG** [comment]
I updated the code and the problem is fixed now. Thank you so much.
Closing.
