### ISSUE TITLE
Filter does not work

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#346]
ffmpeg -f lavfi -i testsrc2 -f lavfi -i aevalsrc="100|9999" -t 10 -c:v ffv1 -c:a flac av_sample.mkv

ffmpeg -i av_sample.mkv -filter_complex "sws_flags=neighbor;format=yuv444p,scale[b];showvolume=w=320:h=40:f=0.95:dm=1[a];[a][b]vstack" -c:v ffv1 -c:a flac -f nut - | ffplay -

sws_flags=neighbor;format=yuv444p,scale[b];showvolume=w=320:h=40:f=0.95:dm=1[a];[a][b]vstack

**Comment by dericed** [comment]
another example:

`ffmpeg -i av_sample.mkv -filter_complex "[0:a:0]abitscope,scale=320x240[z2];[0:v:0]scale=320x240[b];[z2][b]xstack" -f nut - | ffplay -`

**Comment by dericed** [comment]
Or is there an example of a filterchain that does work for filter_complex. I see the README says https://github.com/valbok/QtAVPlayer/blob/8e41b22995e46cee50057e0d2c633a876be184c6/README.md?plain=1#L7 simplified filter_complex support but am not sure what counts as simplified. Ideally I'd want to use multiple input streams to produce one output stream.

**Comment by valbok** [comment]
> Ideally I'd want to use multiple input streams to produce one output stream.
Currently there is only support of _one_ input and multiple outputs.

**Comment by valbok** [comment]
> ffmpeg -i av_sample.mkv -filter_complex "[0:a:0]abitscope,scale=320x240[z2];[0:v:0]scale=320x240[b];[z2][b]xstack" -f nut - | ffplay -

avfilter_graph_parse2  returns AVFilterInOut with AVMEDIA_TYPE_VIDEO for audio input, which was not expected previously. Fixing this

**Comment by valbok** [comment]
> > Ideally I'd want to use multiple input streams to produce one output stream.
> 
> Currently there is only support of _one_ input and multiple outputs.

Meant here there is only one input "-i", but of course filters can have multiple AVFilterInOut inputs

**Comment by dericed** [comment]
Ah thanks. Yes one `-i` but >1 stream references to that input is what I want. More specifically, access to 1 video and 1 audio stream of that input. The examples above call one audio (to abitscope) and one video (to scale) input streams.

I am interested in >1 `-i` inputs but it would be for a later effort. That would be for building a player that can do comparison between two inputs.

**Comment by valbok** [comment]
@dericed Wondering if such filters ("sws_flags=neighbor;format=yuv444p,scale[b];showvolume=w=320:h=40:f=0.95:dm=1[a];[a][b]vstack") require audio and video frames added sequentially, or synced by pts (using av_buffersrc_add_frame_flags).
Means one thread 
1. takes an audio packet and decodes it to audio frame
2. adds to av_buffersrc_add_frame_flags
3. takes a video packet and decodes to video frame
4. adds to av_buffersrc_add_frame_flags
5. reads filtered video frame using av_buffersink_get_frame_flags

Looks like in this case video frame is correct (it is like ffmpeg.c is implemented)

But QAVPlayer has 2 threads, one for audio and one for video. Audio and video frames are added to av_buffersrc_add_frame_flags in parallel and not synced by pts. And video frames are read from av_buffersink_get_frame_flags are not correct in this case.

F.e.
av_buffersrc_add_frame_flags: write video frame with 1.12 pts
reads 3 frames with very weird and old pts:
av_buffersink_get_frame_flags: read 0.12 
av_buffersink_get_frame_flags: read 0.08
av_buffersink_get_frame_flags: read 0.12 


Trying to figure out why filter returns such frames.

**Comment by dericed** [comment]
Hi @valbok, cc'ing @richardpl .

**Comment by richardpl** [comment]
I do not think that concurrently adding frames via >1 threads to buffersrc is valid/correct approach. Some sort of synchronization is needed like mutex. All processing in filtergraphs is sequential only and only threads possible are slice threads in each filter.

EAGAIN from sinks means more input frames are needed to get output frame.
Use av_buffersrc_get_nb_failed_requests() on each buffersrc source input to get which one of them needs more frames received.

**Comment by richardpl** [comment]
Also, ideally input frames should be always referenced.

**Comment by valbok** [comment]
@richardpl Thanks, https://github.com/valbok/QtAVPlayer/pull/349 interesting that magic was in 
```
decoded_frame->pts = av_rescale_delta(decoded_frame_tb, decoded_frame->pts,
                                              AVRational{1, decoded_frame->sample_rate},
                                              decoded_frame->nb_samples,
                                              &d->filter_in_rescale_delta_last,
                                              AVRational{1, decoded_frame->sample_rate});
```
Before sending audio frame, pts is changed, without this, after skipping samples, pts will not be correct (old values)
