### ISSUE TITLE
A complete example is required !

### ISSUE THREAD

**Issue by pingxiangren** [valbok/QtAVPlayer#401]
-  I tried to open the example in that path:
`QtAVPlayer-master\examples\widget_video\widget_video.pro`
- but it did not add QtAVPlayer to the project, so I tried to compile the project in another path:
`QtAVPlayer-master\tests\auto\integration\qavplayer\qavplayer.pro`
- I changed the ffmpeg lib path and INCLUDEPATH of the project so the compilation was successful, but it did not seem to have a ui interface. 
- Can you teach me how to play a video using QtAVPlayer? If possible, please directly add a simple video player that can be directly compiled and opened into the `examples`, thank you!

**Comment by pingxiangren** [comment]
- the `widget_video.pro` is seemed a simple video player what i need , but there is a error like :
`Project ERROR: Unknown module(s) in QT: QtAVPlayer`
- The `QtAVPlayer` is not Qt 5.14.2 official library ,  my `widget_video.pro` is here:
```pro
TEMPLATE = app
TARGET = widget_video

INCLUDEPATH += .

INCLUDEPATH += . ../../src/QtAVPlayer
include(../../src/QtAVPlayer/QtAVPlayer.pri)

QT += gui multimedia multimediawidgets QtAVPlayer
CONFIG += c++11

SOURCES += main.cpp

target.path = $$[QT_INSTALL_EXAMPLES]/$$TARGET
INSTALLS += target

```

**Comment by pingxiangren** [comment]
![Q1111](https://github.com/valbok/QtAVPlayer/assets/77879226/61bd4620-8f18-45df-9720-65f808a91054)

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/commit/259bf266403f7f87ee77422345fa9b5720bcdb68 this is a fix for widget examples

**Comment by valbok** [comment]
Please, feel free to ask any questions

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/403 now only `qmake` is needed
