### ISSUE TITLE
Add CMake support for static lib

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#409]

**Comment by kimvnhung** [comment]
Hope you to finish this issue soon, I expect to use this QtAVPlayer like a library in a CMake project

**Comment by valbok** [comment]
> Hope you to finish this issue soon, I expect to use this QtAVPlayer like a library in a CMake project

Thanks for the interest! First version of QtAVPlayer was implemented as a library and after that decided to bundle the lib directly to the user's project.

So will add `QtAVPlayer.cmake` to be included to the project manually.

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/473/
