### ISSUE TITLE
qml_video example did not stop after the window closed

### ISSUE THREAD

**Issue by on-chip-man** [valbok/QtAVPlayer#411]
when I close the aml_vedio example ,the application does not stop, it seems that the QMutexLocker is locked and waiting forever

**Comment by valbok** [comment]
Hi, thanks for contributing. Could you please share is it Android or Windows? What Qt version is used? Thanks

**Comment by on-chip-man** [comment]
thanks! Qt 5.15.2, Windows 10, msvc64

**Comment by on-chip-man** [comment]
I have figured out that in QAVDemuxer::unload(), we  need unlock before avformat_close_input(&d->ctx);, otherwise it will lock forever in decode_interrupt_cb

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/412
