### ISSUE TITLE
avFormat Options for decrypted video

### ISSUE THREAD

**Issue by binarysoft2011** [valbok/QtAVPlayer#414]
Is there a feature of playing encrypted video with FFmpeg AVOptions?

ffplay video.mp4 -decryption_key decrypt_key.

**Comment by valbok** [comment]
player.setInputOptions({{"decryption_key", "decrypt_key"}}); I never tried, but interesting does it work or not

**Comment by binarysoft2011** [comment]
Great! It's working.
