### ISSUE TITLE
test in deploy another computer, video is played and visible but no audio

### ISSUE THREAD

**Issue by binarysoft2011** [valbok/QtAVPlayer#416]
Developing Computer ASUS 
windows 11 64bit computer
Qt C++ MinGW 32bit 5.12.12
FFmpeg Lib 6.1 built by gcc MinGW 32bit

in Qt Creator test videos are played successfully.
player.exe can be played in this computer.
----------------- below messages are shown in developing windows 11 computer --------------------------
Creating hardware device context: d3d11va
Using hardware device context: d3d11va
durationChanged 60095
mediaStatusChanged LoadedMedia StoppedState
[ 1 ] QMap(("creation_time", "2010-02-09T01:55:39.000000Z")("handler_name", "Apple Video Media Handler")("language", "eng")("vendor_id", "[0][0][0][0]")) 1440 frames, 0.0416667 frame rate ---current
[ 0 ] QMap(("creation_time", "2010-02-09T01:55:39.000000Z")("handler_name", "Apple Sound Media Handler")("language", "eng")("vendor_id", "[0][0][0][0]")) 1295 frames, 0 frame rate ---current
Subtitle streams: 0
stateChanged PlayingState LoadedMedia
h264 : supported hardware device contexts:
    dxva2
    d3d11va
Available pixel formats:
   yuv420p : AVPixelFormat( 0 )
   dxva2_vld : AVPixelFormat( 51 )
   d3d11va_vld : AVPixelFormat( 116 )
   d3d11 : AVPixelFormat( 172 )
Using hardware decoding in d3d11

Then I test in another computer windows 11 64bit.
-----------------below messages are shown in deploy windows 11 computer --------------------------
copied runtime libraries and exe program.

Creating hardware device context: d3d11va
Using hardware device context: d3d11va
durationChanged 60095
mediaStatusChanged LoadedMedia StoppedState
Video streams: 1
[ 1 ] QMap(("creation_time", "2010-02-09T01:55:39.000000Z")("handler_name", "Apple Video Media Handler")("language", "eng")("vendor_id", "[0][0][0][0]")) 1440 frames, 0.0416667 frame rate ---current
Audio streams: 1
[ 0 ] QMap(("creation_time", "2010-02-09T01:55:39.000000Z")("handler_name", "Apple Sound Media Handler")("language", "eng")("vendor_id", "[0][0][0][0]")) 1295 frames, 0 frame rate ---current
Subtitle streams: 0
stateChanged PlayingState LoadedMedia
using null output device, none available
h264 : supported hardware device contexts:
    dxva2
    d3d11va
Available pixel formats:
   yuv420p : AVPixelFormat( 0 )
   dxva2_vld : AVPixelFormat( 51 )
   d3d11va_vld : AVPixelFormat( 116 )
   d3d11 : AVPixelFormat( 172 )
Using hardware decoding in d3d11
using null output device, none available
using null output device, none available
using null output device, none available
using null output device, none available
......................

I changed various video mp4, mpg formats result is same.
videos are played but no audio.

**Comment by binarysoft2011** [comment]
I solved my problem now. I miss to copy qt audio plugin. When I add it, audio is working in deployed computer.

**Comment by valbok** [comment]
Thanks you shared the solution
