### ISSUE TITLE
Add channels to QAVAudioOutput

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#419]

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/422

**Comment by valbok** [comment]
@binarysoft2011

**Comment by binarysoft2011** [comment]
#if QT_VERSION >= QT_VERSION_CHECK(6, 4, 0)
    void setChannelConfig(QAudioFormat::ChannelConfig);
    QAudioFormat::ChannelConfig channelConfig() const;
#endif

What about Qt 5.X ?

**Comment by valbok** [comment]
> #if QT_VERSION >= QT_VERSION_CHECK(6, 4, 0) void setChannelConfig(QAudioFormat::ChannelConfig); QAudioFormat::ChannelConfig channelConfig() const; #endif
> 
> What about Qt 5.X ?

qt5 does not support this
