### ISSUE TITLE
Playback on windows uses a lot of CPU when rendering, despite d3d11 hardware decoding

### ISSUE THREAD

**Issue by geminixdev** [valbok/QtAVPlayer#427]
Decoding works fast and fine, the decoded frames have the format **AV_PIX_FMT_D3D11** in the QAVVideoFrame and in the QVideoFrame **Format_NV12**.

Rendering is to a QVideoSink using 
```
videoSink->setVideoFrame(frame);
```
with the frame as received per QAVPlayer::videoFrame signal.

It works excellently when using a normal decent PC, even in higher resolutions (1080p, 25fps), and also when displaying on 4K screen.

However when using Celeron type CPU the display is not smooth, which becomes visible when displaying on a Full HD monitor. When displaying on a 4k screen the playback is stuttering, also the audio. Then CPU is very high, so that the total CPU of the PC reaches 100%.

When disabling rendering by commenting setVideoFrame() 
```
// videoSink->setVideoFrame(frame)
```
then CPU drops to half or even a third of the value with rendering, and audio is smooth again.

The huge difference in CPU usage is visible on every PC, also on the strong CPUs, only there the playback is still working fine, due to them having enough power.

With this high CPU the Celeron based PCs cannot get used with a 4K monitor, even if the video itself is only HD (720p) or SD. Also the display on a full HD monitor is not perfectly smooth, there are noticeable little jumps from time to time. It is not better than software decoding/rendering.

_Further tests on a PC which does not exceed the 100% CPU, but nevertheless shows slightly stuttering playback:_

I made sure that the timing of the setVideoFrame() calls are ok, they are (for 25 fps) always around 40ms, so the problem is not created before calling setVideoFrame().

Then I checked the timing in the handle() function which gets called after the setVideoFrame() from the Qt library, and there the times are not regular, but vary wildly. Sometimes handle() is called 1 ms after setVideoFrame(), sometimes 10ms later, sometimes even 40ms or more later. Due to that the time between the handle() calls is not regular 40ms, but can be 30ms, or 60 ms, and that seems to cause the visible stuttering.

I don't know how I can influence and fix what is happening after setVideoFrame(), but there seems to be something wrong, probably within Qt. There are Qt bugs about d3d11 rendering, but I'm not sure if they apply here.

This is using Qt 6.6.1 and ffmpeg 5.1.4 on Windows 11, and includes the latest changes in QtAVPlayer code, especially with the d3d33 texture handling. It was tested on 4 different PCs, 1 Ryzen, 1 i7 and 2 Celerons.
(The same code runs fun on Macs, therefore this seems to be a windows only problem.)

**Comment by geminixdev** [comment]
> Then I checked the timing in the handle() function which gets called after the setVideoFrame() from the Qt library, and there the times are not regular, but vary wildly. Sometimes handle() is called 1 ms after setVideoFrame(), sometimes 10ms later, sometimes even 40ms or more later. Due to that the time between the handle() calls is not regular 40ms, but can be 30ms, or 60 ms, and that seems to cause the visible stuttering.

For every setVideoFrame() call there are **3 handle() calls**, which are usually all 3 happening in the same 1 or 2 ms, but sometimes the third can be a few ms later. Looks weird.

**Comment by valbok** [comment]
Each time I check on my Windows 11, never see high CPU. using qml_video example, could you please confirm that you see some perf issues on qml_video? Thanks

**Comment by valbok** [comment]
> with the frame as received per QAVPlayer::videoFrame signal.

Could you confirm that it is Direct connection for Qt6? Otherwise CPU will be used too much to handle frames. For Qt5 it requires to be on main thread, so needs Queued connection

**Comment by geminixdev** [comment]
Thanks, I will test as advised and report.

**Comment by geminixdev** [comment]
> Each time I check on my Windows 11, never see high CPU. using qml_video example, could you please confirm that you see some perf issues on qml_video? Thanks

A quick test with the qml_video example on the (powerful) development PC shows no problem. No performance issues.

I don't know if that makes a difference, but my App uses a QGraphicsView and in that a QGraphicsVideoItem for the video output.

**Comment by geminixdev** [comment]
> > with the frame as received per QAVPlayer::videoFrame signal.
> 
> Could you confirm that it is Direct connection for Qt6? Otherwise CPU will be used too much to handle frames. For Qt5 it requires to be on main thread, so needs Queued connection

You mean to force a direct connection for the     
```
void videoFrame(const QAVVideoFrame &frame);
```
Signal / Slot ? Using something like 
 ```
QObject::connect(&p, &QAVPlayer::videoFrame, this, &FfmpegPlayer::onNewVideoframe, Qt::DirectConnection);
```

I thought that due to using a reference (&frame) and Qt's shallow copies this would not happen. Also in qavplayer.cpp a future is used for decoding, so also in the qml_video example the connection is crossing threads, isn't it?

Nevertheless, I will test it and report.

**Comment by geminixdev** [comment]
> Did you already try to hack to return empty textures to confirm that there is something wrong with rendering? https://github.com/valbok/QtAVPlayer/blob/master/src/QtAVPlayer/qavhwdevice_d3d11.cpp#L196

When running the qml_video example I noticed that it does output "**Only NV12 is supported**" from this handle() function for every frame. So per default the qml_video example does `**return {};`**

This lead me to find that in my App this output did not happen, and I found that the reason was that I didn't have `QT_AVPLAYER_MULTIMEDIA` defined. After adding it, my App does also show this "Only NV12 is supported", thus already runs `return {};`

However it does not make a difference, the performance issue remains.

_But I noticed a fundamental difference:_

In qml_video, when it shows "**Only NV12 is supported**", there the frame().format() is **172 AV_PIX_FMT_D3D11**. 
However in my App the frame().format() is "**-1**".

When checking the frame format right before setVideoFrame(), after the signal slot connection, it is also 172 AV_PIX_FMT_D3D11, but after setVideoFrame() it seems to get lost. May be that gives a hint to what is wrong?

**Comment by geminixdev** [comment]
> > Could you confirm that it is Direct connection for Qt6? Otherwise CPU will be used too much to handle frames. For Qt5 it requires to be on main thread, so needs Queued connection
> 
...
> 
> ```
> QObject::connect(&p, &QAVPlayer::videoFrame, this, &FfmpegPlayer::onNewVideoframe, Qt::DirectConnection);
> ```
> 
> I thought that due to using a reference (&frame) and Qt's shallow copies this would not happen. Also in qavplayer.cpp a future is used for decoding, so also in the qml_video example the connection is crossing threads, isn't it?
> 

Specifying `Qt::DirectConnection` as above in the connect() makes no difference.

**Comment by valbok** [comment]
> my App does also show this "Only NV12 is supported", thus already runs return {};
> In qml_video, when it shows "Only NV12 is supported", there the frame().format() is 172 AV_PIX_FMT_D3D11.

bad news, AFAIK Qt expects to see nv12 with 2 textures to render. No idea how to render AV_PIX_FMT_D3D11 frames here. 
What kind of the stream is it? file or network stream?

Did you try ffplay and confirm that it has d3d11 hw?

**Comment by valbok** [comment]
btw you could try QMediaPlayer to test perf issues, if you don't see, means QAVPlayer needs to be fixed.
```cpp
QMediaPlayer mp;
mp.setSource(file);
auto audioOutput = new QAudioOutput;
mp.setAudioOutput(audioOutput); 
mp.setVideoOutput(videoSurface);
mp.play();
```

**Comment by geminixdev** [comment]
> > my App does also show this "Only NV12 is supported", thus already runs return {};
> > In qml_video, when it shows "Only NV12 is supported", there the frame().format() is 172 AV_PIX_FMT_D3D11.
> 
> bad news, AFAIK Qt expects to see nv12 with 2 textures to render. No idea how to render AV_PIX_FMT_D3D11 frames here. What kind of the stream is it? file or network stream?
> 

The original stream is mpegts (h264/aac) created with ffmpeg, using the standard x264 library as normal with ffmpeg for encoding.

qml_video is tested with the same stream, just transmuxed (not transcoded) to an mp4 container, for easier testing. (As far as I remember I have also tested it with the same file as mpegts, not transmuxed to mp4, and the same result. I will repeat that test.)

Please note that the qml_video performance seems to be perfect despite that it shows AV_PIX_FMT_D3D11 and not NV12 in the handle() function. And in my app it shows in the handle function() as format only "-1".

This is with the **same** h264 encoded source, and with the same ffmpeg library. So I would expect qml_video getting the same performance penalty as my app if it would be a problem with the decoded frames.

So I'm obviously doing something different, which has a terrible effect on performance.

I use the same ffmpeg library in my app and in qml_video, thus it cannot come from there.

So what is different?

- qml_video uses a QVideoSink from QML VideoOutput, and my App uses a QGraphicsVideoItem.
- in qml_video the setVideoFrame() is called from the main() function, main thread, and in my app from a separate thread, in which a "player" class is running in its own thread. 

Could one of that be the reason?

**Comment by geminixdev** [comment]
> > qml_video uses a QVideoSink from QML VideoOutput, and my App uses a QGraphicsVideoItem.
> 
> I can guess, you use `QVideoFrame videoFrame = frame.convertTo(AV_PIX_FMT_RGB32);` since QWidget or QGraphicsItem does not support hw at all and uses QPainter which is CPU based and very slow.

It is definitely not in my app's code, so if that is running then it must be inside QtMM, after setVideoFrame().

Up to setVideoFrame the frame format is definitely still AV_PIX_FMT_D3D11.

I looked also at the code of the widget_video example, also there it is all in the main thread. I have not tested it though, because in the widget_video example you have `QVideoFrame videoFrame = frame.convertTo(AV_PIX_FMT_RGB32);` which would copy the frame to CPU RAM anyway, if I understood correctly. I was wondering already why you have it there.

So a solution might be to change my App to use QML VideoOutput instead of QGraphicsVideoItem? I will try to test that.

**Comment by valbok** [comment]
> So a solution might be to change my App to use QML VideoOutput instead of QGraphicsVideoItem? I will try to test that.

Usually it is first suggestion, AFAIK QWidgets and QGraphicItems are already deprecated for many years. Since hard to adapt hw rendering there via QRHI.

**Comment by valbok** [comment]
> Up to setVideoFrame the frame format is definitely still AV_PIX_FMT_D3D11.

It will try to get a texture via handle() and if it fails it will call map() which will download all memory to CPU. After that the data will be uploaded back to d3d11 textures to render.

**Comment by geminixdev** [comment]
Testresults with the examples, on a recent Celeron N100 CPU. Testfile is a Full  HD (1080p) h264/aac mpegts file (easily playable with every player):

- qml_video: 
  - CPU around 15%, 
  - playback supersmooth, 
  - in handle() showing frame().format() 172 AV_PIX_FMT_D3D11
- widget_video (as is): 
  - CPU around 45%, 
  - playback ok but not very smooth, 
  - in handle() showing frame().format() -1
- widget_video (**without** `frame.convertTo(AV_PIX_FMT_RGB32)`): 
  - CPU 15 - 20%, 
  - playback supersmooth, 
  - in handle() showing frame().format() 172 AV_PIX_FMT_D3D11

So that seems to be it, that high CPU I see in my app too, despite not knowingly having a frame conversion in my code. It seems to be implicit with QGraphicsVideoItem, but not with QML and also not with QVideoWidget.

**Comment by geminixdev** [comment]
Please note that the above tests are not really practicable on a powerful PC. For example my Ryzen 7 development system does not show the CPU differences clearly enough, CPU is simply too low with all the examples. It only shows the same frame formats as the tests with the Celerons, but it has too much power to clearly notice the CPU differences.

Unfortunately the users have more often Celerons than Ryzen 7s ;)

**Comment by valbok** [comment]
> widget_video (without frame.convertTo(AV_PIX_FMT_RGB32))

thanks, looks like it works for Qt6 now, but does not work for Qt5. Glad to hear that.

**Comment by geminixdev** [comment]
This means also that in your **widget_video** example (at least on windows 11, as tested) you don't need to convert the frame to RGB32, and get rewarded with better performance.

**Comment by geminixdev** [comment]
> Testresults with the examples, on a recent Celeron N100 CPU. Testfile is a Full HD (1080p) h264/aac mpegts file (easily playable with every player):
> 
> * qml_video:
>   
>   * CPU around 15%,
>   * playback supersmooth,
>   * in handle() showing frame().format() 172 AV_PIX_FMT_D3D11
> * widget_video (as is):
>   
>   * CPU around 45%,
>   * playback ok but not very smooth,
>   * in handle() showing frame().format() -1
> * widget_video (**without** `frame.convertTo(AV_PIX_FMT_RGB32)`):
>   
>   * CPU 15 - 20%,
>   * playback supersmooth,
>   * in handle() showing frame().format() 172 AV_PIX_FMT_D3D11
> 
> So that seems to be it, that high CPU I see in my app too, despite not knowingly having a frame conversion in my code. It seems to be implicit with QGraphicsVideoItem, but not with QML and also not with QVideoWidget.

To verify the assumption about the implicit convert in QGraphicsVideoItem I replaced the QVideoWidget in the example with a QGraphicsVideoItem in a QGraphicsView / QGraphicsScene.

- widget_video (as is):
   - CPU 35 - 40%%,
   - playback ok, looks smooth
   - in handle() showing frame().format() -1

Interestingly the performance is still better than QVideoWidget with conversion. But it is clearly worse than QML or QVideoWidget without conversion.

So it is confirmed, there is an implicit conversion in the QVideoSink handling within QGraphicsVideoItem. Since QVideoWidget doesn't do that, it looks like a Qt Bug.

**Comment by valbok** [comment]
>in handle() showing frame().format() -1

very sus that it shows -1 as format, means frame is invalid? how is it possible? it should have valid frame when handle() is called.

**Comment by geminixdev** [comment]
> > in handle() showing frame().format() -1
> 
> very sus that it shows -1 as format, means frame is invalid? how is it possible? it should have valid frame when handle() is called.

The `frame().format() -1` comes 
- with QVideoWidget after frame.convertTo(AV_PIX_FMT_RGB32)
- with QGraphicsVideoItem 

Nevertheless the video always gets rendered, just with poor performance.

**Comment by geminixdev** [comment]
And the final confirmation: 

Also in my App I replaced the QGraphicsVideoItem / QGraphicsView / QGraphicsScene with a **QVideoWidget**, and the magic happened, on the same Celeron as above the App shows now the same low CPU as the qml_video and the widget_video (without conversion) examples, **only 15 - 20%!!!**

Now in the app, in the **handle()** function the frame().format() is 172 **AV_PIX_FMT_D3D11**, no more "**-1**",

So it's definitely the QGraphicsVideoItem killing zero copy and pushing the decoded image to CPU RAM.

**Comment by valbok** [comment]
> QGraphicsVideoItem killing zero copy 
>frame().format() is 172 AV_PIX_FMT_D3D11, no more "-1",

but is it still `Only NV12 is supported` ?
Anyway still guessing that there is a copy from GPU to CPU, and maybe upload back to d3d11 texture

**Comment by geminixdev** [comment]
> > QGraphicsVideoItem killing zero copy
> > frame().format() is 172 AV_PIX_FMT_D3D11, no more "-1",
> 
> but is it still `Only NV12 is supported` ? Anyway still guessing that there is a copy from GPU to CPU, and maybe upload back to d3d11 texture

Yes, still `Only NV12 is supported`,  and yes, I think so too, that inside QtMM there is a download to CPU RAM and then upload again, which fortunately seems to be much less load than any conversion.

**Comment by geminixdev** [comment]
So this is not a QtAVPlayer problem, but a Qt Bug with QGraphicsVideoItem. Therefore this issue can get closed.

Thanks very much for your fast replies and your help to identify this, and for creating QtAVPlayer!!!

**Comment by geminixdev** [comment]
Some additional info: 
I tested the same code on a Mac, and to my surprise it showed the same huge CPU difference between QGraphicsVideoItem and QVideoWidget. Thus this is not a windows / d3d11 only problem in QtMM, but it seems to affect all QTMM platforms.

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/453

**Comment by valbok** [comment]
fyi https://github.com/valbok/QtAVPlayer/pull/518 added a gl widget, but also trying to use D3D11 -> OpenGL textures, which is not obvious as thought
