### ISSUE TITLE
Drag play window bug

### ISSUE THREAD

**Issue by samychen** [valbok/QtAVPlayer#452]
When drag and drop the window, duplicate frames will appear, appearing every time

**Comment by samychen** [comment]
The test video resolution is 1080P 59.94fps，Perhaps it is due to the extensive use of lock and wait operations in decoding, resulting in performance degradation

**Comment by samychen** [comment]
The test video resolution is 1080P 59.94fps，Use QAVHWDevice_D3D11 display appearing every time，but cpu render do not appear this bug

**Comment by samychen** [comment]
I finally solved this bug by modify handle method
`    QVariant handle(QRhi *rhi) const override
    {
        if (!rhi || rhi->backend() != QRhi::D3D11)
            return {};

        if (!m_texture) {
            if (frame().format() != AV_PIX_FMT_D3D11) {
                qWarning() << "Only D3D11 is supported, source fmt=" << frame().formatName();
                return {};
            }
            auto av_frame = frame().frame();
            auto texture = (ID3D11Texture2D *)(uintptr_t)av_frame->data[0];
            auto texture_index = (intptr_t)av_frame->data[1];
            if (!texture) {
                qWarning() << "No texture in the frame" << frame().pts();
                return {};
            }
            auto nh = static_cast<const QRhiD3D11NativeHandles *>(rhi->nativeHandles());
            if (!nh) {
                qWarning() << "No QRhiD3D11NativeHandles";
                return {};
            }

            auto dev = reinterpret_cast<ID3D11Device *>(nh->dev);
            if (!dev) {
                qWarning() << "No ID3D11Device device";
                return {};
            }
            auto shared = shareTexture(dev, texture);
            if (shared)
                const_cast<VideoBuffer_D3D11*>(this)->m_texture = copyTexture(dev, get(shared), texture_index);
        }

        QList<quint64> textures = {quint64(get(m_texture))};
        return QVariant::fromValue(textures);
    }`

**Comment by samychen** [comment]
`
    QVariant handle(QRhi *rhi) const override
    {
        if (!rhi || rhi->backend() != QRhi::D3D11)
            return {};

        if (!m_texture) {
            if (frame().format() != AV_PIX_FMT_D3D11) {
                qWarning() << "Only D3D11 is supported, source fmt=" << frame().formatName();
                return {};
            }
            auto av_frame = frame().frame();
            auto texture = (ID3D11Texture2D *)(uintptr_t)av_frame->data[0];
            auto texture_index = (intptr_t)av_frame->data[1];
            if (!texture) {
                qWarning() << "No texture in the frame" << frame().pts();
                return {};
            }
            auto nh = static_cast<const QRhiD3D11NativeHandles *>(rhi->nativeHandles());
            if (!nh) {
                qWarning() << "No QRhiD3D11NativeHandles";
                return {};
            }

            auto dev = reinterpret_cast<ID3D11Device *>(nh->dev);
            if (!dev) {
                qWarning() << "No ID3D11Device device";
                return {};
            }
            auto shared = shareTexture(dev, texture);
            if (shared)
                const_cast<VideoBuffer_D3D11*>(this)->m_texture = copyTexture(dev, get(shared), texture_index);
        }

        QList<quint64> textures = {quint64(get(m_texture))};
        return QVariant::fromValue(textures);
    }
`
I finally solved this bug by modify handle method

**Comment by samychen** [comment]
`
    QVariant handle(QRhi *rhi) const override
    {
        if (!rhi || rhi->backend() != QRhi::D3D11)
            return {};
        if (!m_texture) {
            if (frame().format() != AV_PIX_FMT_D3D11) {
                qWarning() << "Only D3D11 is supported, source fmt=" << frame().formatName();
                return {};
            }
            auto av_frame = frame().frame();
            auto texture = (ID3D11Texture2D *)(uintptr_t)av_frame->data[0];
            auto texture_index = (intptr_t)av_frame->data[1];
            if (!texture) {
                qWarning() << "No texture in the frame" << frame().pts();
                return {};
            }
            auto nh = static_cast<const QRhiD3D11NativeHandles *>(rhi->nativeHandles());
            if (!nh) {
                qWarning() << "No QRhiD3D11NativeHandles";
                return {};
            }

            auto dev = reinterpret_cast<ID3D11Device *>(nh->dev);
            if (!dev) {
                qWarning() << "No ID3D11Device device";
                return {};
            }
            auto shared = shareTexture(dev, texture);
            if (shared)
                const_cast<VideoBuffer_D3D11*>(this)->m_texture = copyTexture(dev, get(shared), texture_index);
        }

        QList<quint64> textures = {quint64(get(m_texture))};
        return QVariant::fromValue(textures);
    }
`
I finally solved this bug by modify handle method

**Comment by valbok** [comment]
Hi, thanks for contributing! What version of Qt is it?

**Comment by valbok** [comment]
- Is it seen using ./qml_example ?
- Could you please share the file?

- btw it is worth to check rendering using QMediaPlayer 
```cpp
QMediaPlayer mp;
mp.setSource(QUrl::fromLocalFile(file));
mp.setAudioOutput(new QAudioOutput); 
mp.setVideoOutput(videoSurface);
mp.play();
```

**Comment by valbok** [comment]
Also as I remember, old Qt QML supports only NV12 format for rendering, means it requires 2 textures, otherwise the renderer will fallback to frame.map(), it will download data from GPU and convert to proper format.

**Comment by valbok** [comment]
Your idea looks correct https://github.com/valbok/QtAVPlayer/pull/453/files
but remember in some version of ffmpeg, AV_PIX_FMT_NV12 is returned for AV_HWDEVICE_TYPE_D3D11VA, maybe it is true for only some files ?

**Comment by valbok** [comment]
Could you confirm that your files are ok now? after 453. Thanks
