### ISSUE TITLE
Does QtAVPlayer work with FFMPEG 7 ?

### ISSUE THREAD

**Issue by geminixdev** [valbok/QtAVPlayer#488]
When looking through qtmultimedia changes update below hints for possible differences with Ffmpeg 7 in hw accelerated decoding and rendering:

https://codereview.qt-project.org/c/qt/qtmultimedia/+/560858

> Old FFmpeg versions expose supported hw formats in codec->pix_fmts,
> whereas FFmpeg 7.0, and partially FFmpeg 6.1, expose the formats in
> hw_config.
> 
> The patch uses both of them to support the best compatibility.
> 
> Pick-to: 6.7 6.5
>

**Comment by OgreTransporter** [comment]
I can confirm that QtAVPlayer is working with Qt 6.7.2 (PR #490 required) and FFmpeg 7.0.1-full_build-www.gyan.dev.

**Comment by geminixdev** [comment]
Yes, I can confirm too, I have it running on Qt 6.6.3 with (self compiled) FFmpeg 7 too, latest from git, on Linux and MacOS. I had to make 3 very minor changes in QtAVPlayer code, easy.
