### ISSUE TITLE
Questions on the widget example

### ISSUE THREAD

**Issue by Ljiaooo** [valbok/QtAVPlayer#489]
Hi, valbok! Thanks for your awasome work. I'm a little bit confused about several lines in the widget example main.cpp file. 

At line 113 and 123 , frame.converTo() returns a QAVVideoFrame object, why this object can be assigned to a QVideoFrame object? Does the QVideoFrame have a constructor that can take value from QVVideoFrame?

**Comment by valbok** [comment]
@Ljiaooo Thanks for your interest!

```cpp
QVideoFrame videoFrame = frame.convertTo(AV_PIX_FMT_RGB32);
```

1. `frame.convertTo(AV_PIX_FMT_RGB32)` reutrns new `QAVVideoFrame`
2. `QAVVideoFrame` could be casted/converted to `QVideoFrame` implicitly using https://github.com/valbok/QtAVPlayer/blob/master/src/QtAVPlayer/qavvideoframe.h#L68

**Comment by Ljiaooo** [comment]
I got it. Thanks for your replay!
