### ISSUE TITLE
Is it possible to set the decoder option using the QtAVPlayer API?

### ISSUE THREAD

**Issue by vladyslav-arzhanov** [valbok/QtAVPlayer#504]
For example, I need to disable the alignment (set the apply_cropping option to 0), but I haven't found a way to do this for my stream, except by writing it `av_opt_set_int(d->avctx, "apply_cropping", 0, 0)` in the QAVCodec before opening the avcodec. Is it possible to set the decoder parameter using the current API, or maybe it needs to be extended?

**Comment by valbok** [comment]
Right now only options for input format is supported: `QAVPlayer::setInputOptions`, but looks it is also interesting to have `QAVPlayer::setCodeOptions` ?

**Comment by vladyslav-arzhanov** [comment]
Yes, that's right

**Comment by vladyslav-arzhanov** [comment]
I have prepared a PR that provides the QAVPlayer::setCodecOptions API https://github.com/valbok/QtAVPlayer/pull/505, could you please review it?

**Comment by vladyslav-arzhanov** [comment]
API has been added, thank you very much
