### ISSUE TITLE
API  access to avformat data

### ISSUE THREAD

**Issue by g-maxime** [valbok/QtAVPlayer#507]
QAVStream, QAVCodec, etc., provide access to underlying FFmpeg structs through the API, but I couldn't find anything for container-level data.

For QCTools, I made a slight modification to QAVPlayer to provide access to the AVFormatContext:
https://github.com/g-maxime/QtAVPlayer/commit/4e8767f62f07396816c03b4c88b936a763c2fe52

I can open a PR if this change is acceptable.

**Comment by valbok** [comment]
>I can open a PR if this change is acceptable.

Thanks, this would be very good
