### ISSUE TITLE
Feature request: allow building against selected ffmpeg on all the platforms

### ISSUE THREAD

**Issue by ElderOrb** [valbok/QtAVPlayer#6]
for example by specifying environment variable(s) FFMPEG / FFMPEG_INCLUDES / FFMPEG_LIBS

**Comment by valbok** [comment]
added cmake support, -DCMAKE_LIBRARY_PATH can be tried to override the path. (Not sure about includes)

**Comment by ElderOrb** [comment]
Great, thanks! At the moment we are still on qmake, but switching to cmake one day doesn't sounds like a big task.

**Comment by ElderOrb** [comment]
But just to clarify, QtAVPlayer is still a 'module', right? So not possible to build against different ffmpeg(s) on the same environment ?

**Comment by valbok** [comment]
it is still a module using qmake

**Comment by valbok** [comment]
```/opt/cmake-3.19.2/bin/cmake .. -DCMAKE_PREFIX_PATH=/opt/dev/qtbase/lib/cmake/Qt5 -DCMAKE_INSTALL_PREFIX=/opt/QtAVPlayer/install -DCMAKE_LIBRARY_PATH="/opt/dev/qtbase/lib;/opt/ffmpeg/install/lib" -DCMAKE_INCLUDE_PATH=/opt/ffmpeg/install/include```

This builds against custom ffmpeg

**Comment by valbok** [comment]
for qmake and linux, need to override pkg-config path (PKG_CONFIG_PATH), 
macOS LIBRARY_PATH
Windows LIB
