### ISSUE TITLE
Recent QtAVPlayer doesn't works incorrectly on windows / Qt 5.15.2

### ISSUE THREAD

**Issue by ElderOrb** [valbok/QtAVPlayer#8]
Finally I've got some time to play with most recent changes (and started with 5.15.2 for simplicity). 

Here is what I've got on windows using qml_video example: 

1. Crash on a code responsible for audio playback. 

![image](https://user-images.githubusercontent.com/23638/112880177-c81fef00-90d2-11eb-95f6-330a06b7aafa.png)

Maybe because of 'QAudioOutput: open error, invalid format.' but it used to work in the past I think... 

2. After commenting out audio-related lines...

If executed from debugger: 

![image](https://user-images.githubusercontent.com/23638/112880373-074e4000-90d3-11eb-996d-bf4d4915faa0.png)

If executed without debugger - window is black (in rare occasions I do see first frame from 'big buck bunny') - and then it crashes in a second.

**Comment by ElderOrb** [comment]
Note: I did experiments with my 'library-friendly' fork, but it shouldn't matter as this fork used to work with original QtAVPlayer

**Comment by ElderOrb** [comment]
Interestingly, just tried the same on ubuntu 18.04 (wsl) - and here it works (at least after commenting out audio-related code)

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/commit/9dc8d8a7ac6681d226845b43101fd2c158724b4a
this might solve audio issue

**Comment by ElderOrb** [comment]
Yep, sound issue is solved, thanks! But pink screen is still here on windows (together with crash if run not under debugger)

**Comment by ElderOrb** [comment]
"h264 : supported hardware device contexts:
    dxva2
    d3d11va
    cuda
Using hardware device context: d3d11va
durationChanged 60095
mediaStatusChanged 2 1
Available pixel formats:
   yuv420p : AVPixelFormat( 0 )
   cuda : AVPixelFormat( 119 )
   dxva2_vld : AVPixelFormat( 53 )
   d3d11va_vld : AVPixelFormat( 118 )
   d3d11 : AVPixelFormat( 174 )
Using hardware decoding in d3d11"

--- is it possible to switch to software decoding on windows just for tests?

**Comment by valbok** [comment]
QT_AVPLAYER_NO_HWDEVICE=1

**Comment by ElderOrb** [comment]
software decoding fixes 'pinkness' & crashes on windows, but its very slow

**Comment by ElderOrb** [comment]
weird, but even with software decoding, 'release' config doesn't work on windows

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/commit/b21e4ba2e97eecffb88bcaa8801ff6612514910d
checked this on windows, seems works

**Comment by ElderOrb** [comment]
yep, works just fine now with both hw/sw decoding!
